Repository briannesbitt/Carbon, pull requests merged in 2018-04, with the labels that each got.

#1245 Document 1.26
  check.php
  docs/index.html
  docs/index.src.html
  history/index.html
  history/index.src.html
Labels: documentation

#1263 Provide diff options for now, yesterday, tomorrow (IT)
  src/Carbon/Lang/it.php
Labels: translation

#1265 Add comparison tests
  tests/Carbon/IsTest.php
Labels: 1.x

#1246 Simpler unit conversions in CarbonInterval
  src/Carbon/Carbon.php
  src/Carbon/CarbonInterval.php
  tests/CarbonInterval/CascadeTest.php
  tests/CarbonInterval/TotalTest.php
Labels: 1.x
