Repository briannesbitt/Carbon, pull requests merged in 2018-05, with the labels that each got.

#1273 Add Diff translations for Dutch
  src/Carbon/Lang/nl.php
Labels: translation

#1274 Add diff translations for Norwegian
  src/Carbon/Lang/no.php
Labels: 1.x, translation

#1275 Add diff translations for Polish
  src/Carbon/Lang/pl.php
Labels: 1.x, translation

#1276 Add diff translations for Slovenian
  src/Carbon/Lang/sl.php
Labels: 1.x, translation

#1283 Add diff translations for Spanish
  src/Carbon/Lang/es.php
Labels: 1.x, translation

#1282 Add diff translations for Catalan
  src/Carbon/Lang/ca.php
Labels: 1.x, translation

#1281 Respect mock instance in createFromFormat with partial format
  src/Carbon/Carbon.php
  tests/Carbon/TestingAidsTest.php
Labels: 1.x

#1277 Add diff translations for Serbian
  src/Carbon/Lang/sr_Cyrl.php
  src/Carbon/Lang/sr_Cyrl_ME.php
  src/Carbon/Lang/sr_Latn_ME.php
Labels: 1.x, translation

#1278 Update phpdoc comment with content from official documentation
  src/Carbon/Carbon.php
Labels: 1.x, documentation

#1284 Occitan translation
  src/Carbon/Lang/oc.php
Labels: 1.x, translation, w8ing for rebase

#1286 Add sw sh ne is zh bs
  src/Carbon/Lang/bs_BA.php
  src/Carbon/Lang/hi.php
  src/Carbon/Lang/is.php
  src/Carbon/Lang/ne.php
  src/Carbon/Lang/sh.php
  src/Carbon/Lang/sw.php
  tests/Localization/BsBaTest.php
  tests/Localization/HiTest.php
  tests/Localization/IsTest.php
  tests/Localization/NeTest.php
  tests/Localization/ShTest.php
  tests/Localization/SwTest.php
Labels: 1.x, translation

#1292 Better translation for korean after/before
  src/Carbon/Lang/ko.php
  tests/Localization/KoTest.php
Labels: 1.x, translation

#1294 Add occitan language
  src/Carbon/Lang/oc.php
  tests/Localization/OcTest.php
Labels: 1.x, translation

#1270 Carbon period from scratch
  phpstan.neon
  phpunit.xml.dist
  src/Carbon/Carbon.php
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/Lang/en.php
  tests/AbstractTestCase.php
  tests/Carbon/DiffTest.php
  tests/Carbon/IsTest.php
  tests/CarbonInterval/SettersTest.php
  tests/CarbonInterval/ToPeriodTest.php
  tests/CarbonPeriod/AliasTest.php
  tests/CarbonPeriod/CreateTest.php
  tests/CarbonPeriod/FilterTest.php
  tests/CarbonPeriod/Fixtures/CarbonPeriodFactory.php
  tests/CarbonPeriod/Fixtures/FooFilters.php
  tests/CarbonPeriod/Fixtures/Mixin.php
  tests/CarbonPeriod/Fixtures/filters.php
  tests/CarbonPeriod/GettersTest.php
  tests/CarbonPeriod/IteratorTest.php
  tests/CarbonPeriod/MacroTest.php
  tests/CarbonPeriod/SettersTest.php
  tests/CarbonPeriod/ToArrayTest.php
  tests/CarbonPeriod/ToStringTest.php
Labels: 1.x

#1298 Implement CarbonInterval macros
  phpstan.neon
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  tests/Carbon/MacroTest.php
  tests/CarbonInterval/Fixtures/Mixin.php
  tests/CarbonInterval/MacroTest.php
Labels: 1.x

#1301 Simplify French short format translations
  src/Carbon/Lang/fr.php
Labels: 1.x, translation

#1306 Delay CarbonPeriod release
  phpstan.neon
  phpunit.xml.dist
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  tests/Carbon/CreateTest.php
  tests/CarbonInterval/ConstructTest.php
  tests/CarbonInterval/ToPeriodTest.php
  tests/CarbonPeriod/AliasTest.php
  tests/CarbonPeriod/CreateTest.php
  tests/CarbonPeriod/FilterTest.php
  tests/CarbonPeriod/Fixtures/CarbonPeriodFactory.php
  tests/CarbonPeriod/Fixtures/FooFilters.php
  tests/CarbonPeriod/Fixtures/Mixin.php
  tests/CarbonPeriod/Fixtures/filters.php
  tests/CarbonPeriod/GettersTest.php
  tests/CarbonPeriod/IteratorTest.php
  tests/CarbonPeriod/MacroTest.php
  tests/CarbonPeriod/SettersTest.php
  tests/CarbonPeriod/ToArrayTest.php
  tests/CarbonPeriod/ToStringTest.php
Labels: 1.x

#1308 Fix bad syntax in unit tests
  tests/Carbon/TestingAidsTest.php
Labels: 1.x

#1309 Add unit test for CarbonInterval::copy() and make()
  tests/Carbon/CreateTest.php
  tests/CarbonInterval/ConstructTest.php
Labels: 1.x

#1302 #1295 Document version 1.28
  check.php
  composer.json
  docs/index.html
  docs/index.src.html
  generate.php
  history/index.html
  history/index.src.html
Labels: 1.x, documentation

#1312 Generate build
  docs/index.html
  history/index.html
Labels: 1.x, documentation

#1313 Add period unit tests
  src/Carbon/CarbonPeriod.php
  tests/Carbon/ArraysTest.php
  tests/Carbon/CreateFromTimeTest.php
  tests/Carbon/PhpBug72338Test.php
  tests/Carbon/RelativeDateStringTest.php
  tests/Carbon/TestingAidsTest.php
  tests/CarbonInterval/CompareTest.php
  tests/CarbonInterval/ToPeriodTest.php
  tests/CarbonPeriod/AliasTest.php
  tests/CarbonPeriod/CreateTest.php
  tests/CarbonPeriod/FilterTest.php
  tests/CarbonPeriod/Fixtures/CarbonPeriodFactory.php
  tests/CarbonPeriod/IteratorTest.php
  tests/CarbonPeriod/MacroTest.php
  tests/CarbonPeriod/SettersTest.php
  tests/CarbonPeriod/ToArrayTest.php
Labels: 1.x

#1307 #1305 Document version 1.29
  CNAME
  check.php
  composer.json
  docs/index.html
  docs/index.src.html
  history/index.html
  history/index.src.html
Labels: 1.x, documentation

#1327 Update de.php
  src/Carbon/Lang/de.php
Labels: 1.x, 2.x, translation

#1334 Handle isNext*, isLast* and microseconds
  phpdoc.php
  src/Carbon/Carbon.php
  src/Carbon/CarbonImmutable.php
  src/Carbon/CarbonInterface.php
  src/Carbon/Traits/Date.php
  tests/Carbon/IsTest.php
  tests/Carbon/SettersTest.php
Labels: 2.x
