Repository briannesbitt/Carbon, pull requests merged in 2018-09, with the labels that each got.

#1431 Implement generic macros
  phpstan.neon
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Macro.php
  src/Carbon/Traits/Options.php
  tests/Carbon/GenericMacroTest.php
  tests/CarbonImmutable/GenericMacroTest.php
Labels: 2.x

#1432 Document 2.1.0
  docs/index.html
  docs/index.src.html
  history/index.html
  history/index.src.html
  reference/index.html
Labels: 2.x, documentation

#1436 Fix #1435 New in carbon 2
  docs/index.html
  docs/index.src.html
  e.php
  history/index.html
  reference/index.html
Labels: 2.x, documentation

#1438 Fix abbreviations
  src/Carbon/Lang/ru.php
Labels: 1.x, translation

#1439 Add ru abbreviations
  src/Carbon/Lang/ru.php
  tests/Localization/RuTest.php
Labels: 2.x, translation

#1440 Add interface_exists check - fixed in 2.x by #1430
  src/JsonSerializable.php
Labels: 1.x

#1442 Fix GitHub Capitalize in docs
  contribute/index.html
  docs/index.html
  history/index.html
  index.html
  template.src.html
Labels: documentation

#1444 Implement getSettings() and locale propagation #1443
  src/Carbon/CarbonInterface.php
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/Factory.php
  src/Carbon/FactoryImmutable.php
  src/Carbon/Traits/Options.php
  tests/Carbon/SettingsTest.php
  tests/CarbonInterval/SettersTest.php
  tests/CarbonPeriod/IteratorTest.php
Labels: 2.x, enhancement
