Repository briannesbitt/Carbon, pull requests merged in 2018-06, with the labels that each got.

#1362 Update pt_BR Language
  src/Carbon/Lang/pt_BR.php
Labels: 1.x, translation

#1365 Myanmar language for diffForHumans function translation
  src/Carbon/Lang/my.php
  tests/Localization/MyTest.php
Labels: 1.x, translation

#1363 Automate synchronization with Laravel locale
  .gitattributes
  composer.json
  phpstan.neon
  phpunit.xml.dist
  src/Carbon/Laravel/ServiceProvider.php
  tests/AbstractTestCase.php
  tests/Laravel/App.php
  tests/Laravel/EventDispatcher.php
  tests/Laravel/ServiceProvider.php
  tests/Laravel/ServiceProviderTest.php
Labels: 1.x

#1367 More precise localeHasShortUnits
  src/Carbon/Carbon.php
  src/Carbon/Lang/fr.php
  tests/Carbon/LocalizationTest.php
Labels: 1.x, translation

#1370 do not use global static proxy as global aliases are not always confi…
  src/Carbon/Laravel/ServiceProvider.php
Labels: 1.x

#1373 [i18n]Occitan update for #1367
  src/Carbon/Lang/oc.php
Labels: 1.x, translation

#1377 Spelling: documenation -> documentation
  contribute/index.html
  contribute/index.src.html
Labels: documentation
