Repository briannesbitt/Carbon, pull requests merged in 2018-07, with the labels that each got.

#1378 Add mutable/immutable converters
  src/Carbon/Traits/Date.php
  tests/Carbon/InstanceTest.php
  tests/CarbonImmutable/InstanceTest.php
Labels: 2.x

#1380 Added Ukrainian translation
  src/Carbon/Lang/uk.php
Labels: translation

#1381 Added short units for pt_BR translation
  src/Carbon/Lang/pt_BR.php
Labels: translation

#1382 Wrong day of a week exception
  src/Carbon/Carbon.php
  tests/Carbon/SetStartEndOfWeekTest
Labels: 1.x

#1393 Change before yesterday Spanish translation
  src/Carbon/Lang/es.php
Labels: 1.x, translation

#1396 Support closure based $toStringFormat
  src/Carbon/Carbon.php
  tests/Carbon/StringsTest.php
Labels: 1.x

#1403 Patch catalan translation
  src/Carbon/Lang/ca.php
  tests/Localization/CaTest.php
Labels: 1.x, translation
