Repository briannesbitt/Carbon, pull requests merged in 2018-08, with the labels that each got.

#1406 Full Translation Added
  src/Carbon/Lang/bn.php
Labels: 1.x, translation

#1414 Document 1.33
  docs/index.html
  docs/index.src.html
  history/index.html
  history/index.src.html
Labels: 1.x, documentation

#1418 [i18n]Occitan: correction linked to #1403
  src/Carbon/Lang/oc.php
  tests/Localization/OcTest.php
Labels: 2.x, translation

#1420 Local options
  phpdoc.php
  phpunit.xml.dist
  src/Carbon/Carbon.php
  src/Carbon/CarbonImmutable.php
  src/Carbon/CarbonInterface.php
  src/Carbon/Factory.php
  src/Carbon/FactoryImmutable.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Difference.php
  src/Carbon/Traits/Localization.php
  src/Carbon/Traits/Options.php
  src/Carbon/Traits/Serialization.php
  src/Carbon/Traits/Test.php
  src/Carbon/Traits/Units.php
  tests/Carbon/SettersTest.php
  tests/Carbon/SettingsTest.php
  tests/CarbonImmutable/SettersTest.php
  tests/CarbonImmutable/SettingsTest.php
  tests/Factory/FactoryTest.php
Labels: 2.x

#1425 Update sl.php
  src/Carbon/Lang/sl.php
  tests/Localization/SlTest.php
Labels: 2.x

#1430 Add interface_exists check
  src/JsonSerializable.php
Labels: 2.x
