Repository briannesbitt/Carbon, pull requests merged in 2018-11, with the labels that each got.

#1499 Fix #1497 hasFormat more strict with full-year
  src/Carbon/Carbon.php
  tests/Carbon/IsTest.php
  tests/CarbonPeriod/AliasTest.php
Labels: 1.x

#1498 Fix #1497 hasFormat more strict with full-year
  src/Carbon/Traits/Options.php
  tests/Carbon/IsTest.php
  tests/CarbonImmutable/IsTest.php
  tests/CarbonInterval/AddTest.php
  tests/CarbonPeriod/AliasTest.php
Labels: 2.x

#1513 Test all version that changed PHP date behavior
  .travis.yml
Labels: 2.x

#1514 Travis patch versions
  .travis.yml
  tests/AbstractTestCase.php
  tests/Carbon/CreateFromTimeStringTest.php
  tests/Carbon/CreateFromTimestampTest.php
  tests/Carbon/CreateSafeTest.php
  tests/Carbon/DiffTest.php
  tests/Carbon/GettersTest.php
  tests/Carbon/InstanceTest.php
  tests/Carbon/IsTest.php
  tests/Carbon/JsonSerializationTest.php
  tests/Carbon/MacroTest.php
  tests/Carbon/PhpBug72338Test.php
  tests/Carbon/StartEndOfTest.php
  tests/CarbonInterval/MacroTest.php
  tests/CarbonPeriod/MacroTest.php
Labels: 1.x

#1518 Fix bad interval detection
  src/Carbon/Traits/Difference.php
  tests/Carbon/DiffTest.php
  tests/CarbonImmutable/DiffTest.php
Labels: 2.x

#1521 Increase precision for closest/farthest/average
  src/Carbon/Carbon.php
  tests/Carbon/ComparisonTest.php
  tests/Carbon/CreateFromTimestampTest.php
  tests/Carbon/DiffTest.php
  tests/Carbon/GettersTest.php
  tests/Carbon/InstanceTest.php
  tests/Carbon/StartEndOfTest.php
Labels: 1.x, enhancement

#1520 Increase precision for closest/farthest/average
  src/Carbon/Traits/Modifiers.php
  src/Carbon/Traits/Units.php
  tests/Carbon/ComparisonTest.php
  tests/Carbon/StartEndOfTest.php
  tests/CarbonImmutable/ComparisonTest.php
  tests/CarbonImmutable/StartEndOfTest.php
Labels: 2.x, enhancement

#1525 Estonian and Portuguese languages update
  src/Carbon/Lang/et.php
  src/Carbon/Lang/pt.php
  tests/Localization/EtTest.php
Labels: 2.x, translation

#1526 Update hr.php
  src/Carbon/Lang/hr.php
  tests/Localization/HrTest.php
Labels: 2.x, translation

#1527 Add methods add/sub/diffIn milliseconds
  src/Carbon/Carbon.php
  src/Carbon/CarbonImmutable.php
  src/Carbon/CarbonInterface.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Difference.php
  src/Carbon/Traits/Units.php
  tests/Carbon/AddTest.php
  tests/Carbon/ModifyTest.php
  tests/CarbonImmutable/AddTest.php
  tests/CarbonImmutable/ModifyTest.php
Labels: 2.x, enhancement

#1532 #1530 Fix sign addition
  src/Carbon/CarbonInterval.php
  tests/CarbonInterval/AddTest.php
Labels: 2.x, bug

#1531 Contributing guide
  contributing.md
Labels: documentation
