Repository briannesbitt/Carbon, pull requests merged in 2018-10, with the labels that each got.

#1451 Update the documents to use the longer format functions as a default
  docs/index.html
  docs/index.src.html
Labels: documentation

#1449 Update Lithuanian language
  src/Carbon/Lang/lt.php
Labels: 2.x, translation

#1457 Update Lithuanian language and tests
  src/Carbon/Lang/lt.php
  tests/Localization/LtTest.php
Labels: 2.x, translation

#1455 Set correctly phpDocs
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonTimeZone.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Difference.php
  src/Carbon/Traits/Macro.php
Labels: 2.x

#1460 Fix #1458 Handle multiple forms for day/month names in translation
  src/Carbon/CarbonInterface.php
  src/Carbon/Lang/ru.php
  src/Carbon/Traits/Date.php
  tests/Carbon/LocalizationTest.php
Labels: 2.x, translation

#1459 Run locale update only if services are registered
  src/Carbon/Laravel/ServiceProvider.php
  tests/Laravel/App.php
  tests/Laravel/ServiceProviderTest.php
Labels: 2.x, enhancement

#1468 #1458 Properly handle multiple forms for days and months names
  src/Carbon/Lang/be.php
  src/Carbon/Lang/ca.php
  src/Carbon/Lang/el.php
  src/Carbon/Lang/hr.php
  src/Carbon/Lang/hy.php
  src/Carbon/Lang/hy_AM.php
  src/Carbon/Lang/ka.php
  src/Carbon/Lang/ru.php
  src/Carbon/Lang/uk.php
  src/Carbon/Traits/Date.php
  tests/Carbon/LocalizationTest.php
  tests/CarbonImmutable/LocalizationTest.php
  tests/Localization/BeTest.php
  tests/Localization/UkTest.php
Labels: 2.x, translation

#1466 Unify add/sub/subtract prototypes for Carbon and CarbonInterval
  src/Carbon/CarbonInterval.php
  src/Carbon/Traits/Units.php
  tests/CarbonInterval/AddTest.php
Labels: 2.x, enhancement

#1467 #1448 Implement float difference methods
  src/Carbon/Traits/Difference.php
  tests/Carbon/DiffTest.php
Labels: 2.x, enhancement

#1470 Document 2.4.0
  check.php
  contribute/index.html
  docs/index.html
  docs/index.src.html
  e.php
  history/index.html
  history/index.src.html
  index.html
  reference/index.html
  template.src.html
Labels: 2.x, documentation

#1471 Fix IT lang last day translation
  src/Carbon/Lang/it.php
  tests/Localization/ItTest.php
Labels: 2.x, translation

#1476 Fix IT lang last day translation
  src/Carbon/Lang/it.php
  tests/Localization/ItTest.php
Labels: 2.x, translation

#1475 Fix IT lang last day translation
  src/Carbon/Lang/it.php
  tests/Localization/ItTest.php
Labels: 2.x, translation

#1474 Fix IT lang last day translation
  src/Carbon/Lang/it.php
  tests/Localization/ItTest.php
Labels: 2.x, translation

#1473 Fix IT lang last day translation
  src/Carbon/Lang/it.php
  tests/Localization/ItTest.php
Labels: 2.x, translation

#1472 Fix IT lang last day translation
  src/Carbon/Lang/it.php
  tests/Localization/ItTest.php
Labels: 2.x, translation

#1480 Fixed short time format for id lang
  src/Carbon/Lang/id.php
  tests/Localization/IdTest.php
Labels: 2.x, translation

#1486 Improve milliseconds/microseconds support
  src/Carbon/CarbonInterval.php
  tests/AbstractTestCase.php
  tests/CarbonInterval/AddTest.php
  tests/CarbonInterval/TotalTest.php
Labels: 2.x

#1487 Document version 2.5.0
  docs/index.html
  history/index.html
  history/index.src.html
  reference/index.html
Labels: 2.x, documentation

#1488 Add php 7.3 to travis
  .travis.yml
  composer.json
Labels: 2.x
