Repository briannesbitt/Carbon, pull requests merged in 2018-02, with the labels that each got.

#886 Fix issue #885
  .gitattributes
Labels: 1.x

#1087 travisci and styleci configuration upgrade
  .gitignore
  .php_cs.dist
  .travis.yml
  phpstan.neon
  src/Carbon/Carbon.php
  src/Carbon/CarbonInterval.php
  src/Carbon/Lang/bg.php
  tests/Carbon/AddMonthsTest.php
  tests/Carbon/ExpressiveComparisonTest.php
  tests/Localization/UkTest.php
Labels: bug

#1055 Fix issue with mocking time on PHP >=7.1
  src/Carbon/Carbon.php
  tests/Carbon/ConstructTest.php
Labels: bug, w8ing for rebase

#934 Minor phpdoc fix
  src/Carbon/Carbon.php
Labels: w8ing for rebase

#1091 Removed date() and time() functions from Carbon::create()
  src/Carbon/Carbon.php
  tests/Carbon/CreateFromTimeTest.php
Labels: bug

#901 Minor fix to Azerbaijani localization
  src/Carbon/Lang/az.php
  tests/Localization/AzTest.php
Labels: 1.x, translation, w8ing for rebase

#941 Fix typo in zh_TW
  src/Carbon/Lang/zh_TW.php
Labels: translation

#963 Fix traditional Chinese language, extra space removed and '周' shall be '週'
  src/Carbon/Lang/zh_TW.php
Labels: translation

#772 Add support for number of interval pieces to diffForHumans
  src/Carbon/Carbon.php
  tests/Localization/EnTest.php
Labels: 1.x

#989 Document createFromTimestampMs method.
  docs/index.html
  docs/index.src.html
Labels: documentation

#1097 Document is methods
  .travis.yml
  check.php
  docs/index.html
  docs/index.src.html
  generate.php
Labels: documentation

#895 Add more serialization tests (Fix issue #894)
  tests/Carbon/SerializationTest.php
Labels: 1.x

#900 Fixing #871, workaround of php bug [72338](https://bugs.php.net/bug.php?id=72338)
  src/Carbon/Carbon.php
  tests/Carbon/PhpBug72338Test.php
Labels: 1.x, bug

#1017 Optimize the magic properties getter
  src/Carbon/Carbon.php
Labels: enhancement

#1107 Fix issue [#1081](https://github.com/briannesbitt/Carbon/issues/1081)
  src/Carbon/Carbon.php
Labels: bug

#892 Fixed issue #891 - getLastErrors
  src/Carbon/Carbon.php
  tests/Carbon/LastErrorTest.php
Labels: 1.x, bug

#1104 Add arguments check
  .gitignore
  check.php
  docs/index.html
  docs/index.src.html
  generate.php
  index.html
Labels: documentation

#1101 Add docs for Carbon::setUtf8
  docs/index.src.html
Labels: documentation

#1102 Update the history
  history/index.html
  history/index.src.html
Labels: documentation

#1115 Translation ar shakl
  .gitignore
  phpstan.neon
  src/Carbon/Lang/ar_shakl.php
  tests/Localization/ArShaklTest.php
Labels: translation

#975 Fix Slovak language - Add declensions
  src/Carbon/Lang/sk.php
Labels: translation

#996 Add Armenian Language Localization
  src/Carbon/Lang/arm.php
  tests/Carbon/LocalizationTest.php
  tests/Localization/ArmTest.php
Labels: translation

#967 Add Pashto (PS) Language
  src/Carbon/Lang/ps.php
  tests/Localization/PsTest.php
Labels: need investigation, translation

#1036 Fix uz.php
  src/Carbon/Lang/uz.php
Labels: translation

#1015 Kazakh language support
  src/Carbon/Lang/kk.php
Labels: translation, w8ing for rebase

#1041 Improved translation
  src/Carbon/Lang/mn.php
Labels: translation

#1106 Locale dv mv
  src/Carbon/Lang/dv_MV.php
  tests/Localization/DvMvTest.php
Labels: translation

#972 Add Serbian (Cyrillic) Language
  src/Carbon/Lang/sr_Cyrl.php
Labels: translation

#898 Provide RFC7231 formating
  src/Carbon/Carbon.php
  tests/Carbon/StringsTest.php
Labels: 1.x, enhancement
