Repository briannesbitt/Carbon, pull requests merged in 2018-12, with the labels that each got.

#1539 [i18n]Update Occitan: + format, +calendar, ...
  src/Carbon/Lang/oc.php
  tests/Localization/OcTest.php
Labels: translation

#1540 Fix #1537 Resolve mixed signs on cascade() call
  src/Carbon/CarbonInterval.php
  tests/CarbonInterval/CascadeTest.php
Labels: 2.x, enhancement

#1551 Updated the Norwegian translation
  src/Carbon/Lang/no.php
Labels: 2.x, translation
