Repository briannesbitt/Carbon, pull requests merged in 2019-08, with the labels that each got.

#1825 Add CarbonPeriod methods
  src/Carbon/CarbonInterface.php
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Rounding.php
  src/Carbon/Traits/Units.php
  tests/Carbon/RoundTest.php
  tests/CarbonInterval/RoundingTest.php
  tests/CarbonPeriod/ComparisonTest.php
  tests/CarbonPeriod/GettersTest.php
  tests/CarbonPeriod/RoundingTest.php
Labels: enhancement

#1826 Add cast() method and traits mixins to CarbonInterval and CarbonPeriod
  phpstan.neon
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/CarbonTimeZone.php
  src/Carbon/Traits/Cast.php
  src/Carbon/Traits/Macro.php
  src/Carbon/Traits/Mixin.php
  src/Carbon/Traits/Mutability.php
  tests/Carbon/Fixtures/FooBar.php
  tests/Carbon/MacroTest.php
  tests/CarbonPeriod/CreateTest.php
Labels: enhancement

#1827 #1822 Use less short variants for short units in Polish
  .travis.yml
  src/Carbon/Lang/pl.php
  src/Carbon/Traits/Date.php
  tests/Carbon/GenericMacroTest.php
  tests/CarbonImmutable/GenericMacroTest.php
  tests/Localization/PlPlTest.php
  tests/Localization/PlTest.php
Labels: translation

#1830 Implement contains() and JsonSerializable in CarbonPeriod
  .php_cs.dist
  src/Carbon/CarbonPeriod.php
  tests/CarbonPeriod/ComparisonTest.php
Labels: enhancement

#1832 Fix #1831 Refresh global translator caching
  src/Carbon/Translator.php
  tests/Language/TranslatorTest.php
Labels: bug

#1833 Improve cast methods
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/CarbonTimeZone.php
  src/Carbon/Traits/Cast.php
  src/Carbon/Traits/Converter.php
  tests/Carbon/InstanceTest.php
  tests/Carbon/ObjectsTest.php
  tests/CarbonImmutable/InstanceTest.php
  tests/CarbonImmutable/ObjectsTest.php
  tests/CarbonInterval/ToDateIntervalTest.php
  tests/CarbonPeriod/CreateTest.php
  tests/CarbonPeriod/ToDatePeriodTest.php
Labels: enhancement

#1835 Fix #1834 language detection in Lumen
  src/Carbon/Laravel/ServiceProvider.php
Labels: bug

#1838 Add altNumbers option to forHumans/diffForHumans
  src/Carbon/CarbonInterval.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Localization.php
  tests/CarbonInterval/AlternativeNumbersTest.php
  tests/Localization/BnBdTest.php
  tests/Localization/BnInTest.php
  tests/Localization/BnTest.php
  tests/Localization/MyMmTest.php
  tests/Localization/MyTest.php
  tests/Localization/OrInTest.php
  tests/Localization/OrTest.php
Labels: enhancement, translation

#1841 Fix #1840 add short form or year for year in Turkish
  .travis.yml
  phpdoc.php
  src/Carbon/CarbonInterface.php
  src/Carbon/Lang/tr.php
  src/Carbon/Traits/Converter.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Difference.php
  src/Carbon/Traits/Modifiers.php
  src/Carbon/Traits/Serialization.php
  tests/Carbon/WeekTest.php
  tests/CarbonImmutable/WeekTest.php
  tests/Localization/TrCyTest.php
  tests/Localization/TrTest.php
  tests/Localization/TrTrTest.php
Labels: translation

#1839 Fix #1837 fixed from_now translation in Fnnish and add few seconds
  src/Carbon/Lang/fi.php
  tests/Localization/FiFiTest.php
  tests/Localization/FiTest.php
Labels: translation

#1836 Document 2.23
  composer.json
  contribute/docs/index.html
  contribute/translators/index.html
  docs/index.html
  docs/index.src.html
  index.html
  index.src.html
  reference/index.html
  tools/check.php
  tools/config.php
  tools/methods.php
Labels: documentation

#1852 Fix #1851 Update all Carbon classes on Laravel locale change
  src/Carbon/Laravel/ServiceProvider.php
Labels: bug, translation

#1847 [AR] Update with enhancements
  src/Carbon/Lang/ar.php
  src/Carbon/Lang/ar_DZ.php
  src/Carbon/Lang/ar_KW.php
  src/Carbon/Lang/ar_LY.php
  src/Carbon/Lang/ar_MA.php
  src/Carbon/Lang/ar_SA.php
  src/Carbon/Lang/ar_Shakl.php
  src/Carbon/Lang/ar_TN.php
  tests/Localization/ArAeTest.php
  tests/Localization/ArBhTest.php
  tests/Localization/ArDjTest.php
  tests/Localization/ArDzTest.php
  tests/Localization/ArEgTest.php
  tests/Localization/ArEhTest.php
  tests/Localization/ArErTest.php
  tests/Localization/ArIlTest.php
  tests/Localization/ArInTest.php
  tests/Localization/ArIqTest.php
  tests/Localization/ArJoTest.php
  tests/Localization/ArKmTest.php
  tests/Localization/ArKwTest.php
  tests/Localization/ArLbTest.php
  tests/Localization/ArLyTest.php
  tests/Localization/ArMaTest.php
  tests/Localization/ArMrTest.php
  tests/Localization/ArOmTest.php
  tests/Localization/ArPsTest.php
  tests/Localization/ArQaTest.php
  tests/Localization/ArSaTest.php
  tests/Localization/ArSdTest.php
  tests/Localization/ArShaklTest.php
  tests/Localization/ArSoTest.php
  tests/Localization/ArSsTest.php
  tests/Localization/ArSyTest.php
  tests/Localization/ArTdTest.php
  tests/Localization/ArTest.php
  tests/Localization/ArTnTest.php
  tests/Localization/ArYeTest.php
Labels: translation

#1859 Implement #1856 handle string in is same methods
  phpdoc.php
  src/Carbon/Carbon.php
  src/Carbon/CarbonImmutable.php
  src/Carbon/CarbonInterface.php
  src/Carbon/Exceptions/BadUnitException.php
  src/Carbon/Traits/Comparison.php
  src/Carbon/Traits/Date.php
  tests/Carbon/IsTest.php
  tests/CarbonImmutable/IsTest.php
Labels: enhancement

#1863 Fix #1861 Add aUnit option in Thai
  src/Carbon/Lang/th.php
  tests/Localization/ThTest.php
  tests/Localization/ThThTest.php
Labels: translation

#1862 Fix #1860 Allow Closure in setTestNow()
  src/Carbon/Traits/Creator.php
  src/Carbon/Traits/Test.php
  tests/Carbon/TestingAidsTest.php
  tests/CarbonImmutable/TestingAidsTest.php
Labels: enhancement

#1867 Fix #1842 Latvian declension, aUnit and short units
  src/Carbon/Lang/lv.php
  src/Carbon/Lang/mn.php
  src/Carbon/Lang/sl.php
  tests/Localization/LvLvTest.php
  tests/Localization/LvTest.php
Labels: translation

#1869 Fix #1849 Slovenian unit declensions
  src/Carbon/CarbonInterval.php
  src/Carbon/Lang/hu.php
  src/Carbon/Lang/sl.php
  tests/Localization/HuHuTest.php
  tests/Localization/HuTest.php
  tests/Localization/SlSiTest.php
  tests/Localization/SlTest.php
Labels: translation

#1873 Add the most relevant info on how to contribute to the docs to the top
  contribute/docs/index.src.html
Labels: documentation

#1875 Fix #1857 static methods typing autocompletion
  phpdoc.php
  src/Carbon/Carbon.php
  src/Carbon/CarbonImmutable.php
  src/Carbon/CarbonInterface.php
  src/Carbon/Factory.php
  src/Carbon/FactoryImmutable.php
Labels: enhancement

#1872 Fix #1800 Lithuanian declensions
  src/Carbon/Lang/lt.php
  tests/Localization/LtLtTest.php
  tests/Localization/LtTest.php
Labels: help wanted, translation

#1866 Document version 2.24
  composer.json
  contribute/translators/index.html
  docs/index.html
  docs/index.src.html
  index.html
  reference/index.html
  tools/check.php
  tools/config.php
  tools/generate.php
  tools/methods.php
Labels: documentation
