Repository briannesbitt/Carbon, pull requests merged in 2019-09, with the labels that each got.

#1878 Fix #1877 Support timezone short offset format
  src/Carbon/CarbonTimeZone.php
  src/Carbon/Traits/Date.php
  tests/Carbon/CreateFromTimestampTest.php
Labels: bug

#1876 #1814 Implement PHP 8 compliant macro syntax
  phpunit.xml.dist
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Mixin.php
  tests/Carbon/GenericMacroTest.php
  tests/CarbonImmutable/GenericMacroTest.php
  tests/CommonTraits/MacroContextNestingTest.php
Labels: enhancement

#1883 Fix isBefore documentation
  src/Carbon/CarbonInterface.php
Labels: documentation

#1887 Fix #1886 Support slashes in hasFormat()
  src/Carbon/Traits/Comparison.php
  tests/Carbon/IsTest.php
  tests/CarbonImmutable/IsTest.php
Labels: bug

#1899 #1893 Fix Ukrainian units translation
  src/Carbon/CarbonInterval.php
  src/Carbon/Lang/uk.php
  tests/Localization/UkTest.php
  tests/Localization/UkUaTest.php
Labels: translation

#1898 #1889 Fix Belarusian units translations
  src/Carbon/Lang/be.php
  src/Carbon/Lang/uk.php
  tests/Localization/BeByLatinTest.php
  tests/Localization/BeByTest.php
  tests/Localization/BeTest.php
Labels: translation
