Repository briannesbitt/Carbon, pull requests merged in 2019-11, with the labels that each got.

#1928 Add diff translate
  src/Carbon/Lang/ru.php
Labels: translation

#1933 Fix #1927 Finnish future interval translations
  src/Carbon/Lang/fi.php
  tests/Localization/FiFiTest.php
  tests/Localization/FiTest.php
Labels: translation

#1937 Allow Symfony 5
  composer.json
Labels: enhancement

#1936 Fix #1929 Indonesian from now translation
  src/Carbon/Lang/id.php
  src/Carbon/Lang/in.php
  src/Carbon/Lang/ms.php
  src/Carbon/Lang/ru.php
  tests/Localization/IdIdTest.php
  tests/Localization/IdTest.php
  tests/Localization/InTest.php
  tests/Localization/MsBnTest.php
  tests/Localization/MsMyTest.php
  tests/Localization/MsSgTest.php
  tests/Localization/MsTest.php
Labels: translation

#1938 Fix #1908 Korean spacing and aUnit option
  src/Carbon/Lang/ko.php
  tests/Localization/KoKpTest.php
  tests/Localization/KoKrTest.php
  tests/Localization/KoTest.php
Labels: translation

#1940 Added diff before_yesterday and after_tomorrow
  src/Carbon/Lang/ru.php
Labels: translation

#1942 Optimize Travis-CI build
  .travis.yml
  src/Carbon/Lang/be.php
  src/Carbon/Lang/bm.php
  src/Carbon/Lang/br.php
  src/Carbon/Lang/cv.php
  src/Carbon/Lang/dv.php
  src/Carbon/Lang/dv_MV.php
  src/Carbon/Lang/ga.php
  src/Carbon/Lang/gd.php
  src/Carbon/Lang/kk.php
  src/Carbon/Lang/ky.php
  src/Carbon/Lang/lo.php
  src/Carbon/Lang/me.php
  src/Carbon/Lang/mi.php
  src/Carbon/Lang/my.php
  src/Carbon/Lang/oc.php
  src/Carbon/Lang/scr.php
  src/Carbon/Lang/sd.php
  src/Carbon/Lang/se.php
  src/Carbon/Lang/sh.php
  src/Carbon/Lang/si.php
  src/Carbon/Lang/sr.php
  src/Carbon/Lang/sr_Latn_ME.php
  src/Carbon/Lang/ss.php
  src/Carbon/Lang/tet.php
  src/Carbon/Lang/tg.php
  src/Carbon/Lang/tl.php
  src/Carbon/Lang/tlh.php
  src/Carbon/Lang/tzl.php
  src/Carbon/Lang/tzm.php
  src/Carbon/Lang/tzm_Latn.php
  src/Carbon/Lang/ug.php
  src/Carbon/Lang/uz.php
  src/Carbon/Lang/uz_Latn.php
  src/Carbon/Lang/yo.php
  src/Carbon/Traits/Localization.php
  src/Carbon/Translator.php
  tests/AbstractTestCase.php
  tests/Carbon/LocalizationTest.php
  tests/Carbon/MacroTest.php
  tests/CarbonImmutable/LocalizationTest.php
  tests/CarbonImmutable/MacroTest.php
  tests/Localization/DvMvTest.php
  tests/Localization/LocalizationTestCase.php
  tests/Localization/MeTest.php
  tests/Localization/SrCyrlBaTest.php
  tests/Localization/SrCyrlMeTest.php
  tests/Localization/SrCyrlTest.php
  tests/Localization/SrCyrlXkTest.php
  tests/Localization/SrLatnBaTest.php
  tests/Localization/SrLatnMeTest.php
  tests/Localization/SrLatnTest.php
  tests/Localization/SrLatnXkTest.php
  tests/Localization/SrMeTest.php
  tests/Localization/SrRsLatinTest.php
  tests/Localization/SrRsTest.php
  tests/Localization/SrTest.php
  tests/Symfony/Component/Translation/TranslatorInterface.php
Labels: enhancement

#1930 Add option for rounding in forHumans
  phpmd.xml
  src/Carbon/CarbonInterface.php
  src/Carbon/CarbonInterval.php
  tests/CarbonInterval/ForHumansTest.php
Labels: enhancement

#1921 Add createFromFormat static method to CarbonInterval
  src/Carbon/CarbonInterval.php
  src/Carbon/Exceptions/ParseErrorException.php
  tests/CarbonInterval/CreateFromFormatTest.php
Labels: enhancement

#1922 Document CarbonInterval::createFromFormat
  docs/index.src.html
  tools/check.php
Labels: documentation
