Repository briannesbitt/Carbon, pull requests merged in 2019-03, with the labels that each got.

#1639 Update it.php
  src/Carbon/Lang/it.php
Labels: translation

#1650 Fix addRealMicrosecond() with low float precision
  src/Carbon/Traits/Units.php
  tests/Carbon/ModifyTest.php
Labels: enhancement

#1654 Custom format function
  phpunit.xml.dist
  src/Carbon/CarbonInterface.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/Factory.php
  src/Carbon/FactoryImmutable.php
  src/Carbon/Lang/ru.php
  src/Carbon/Traits/Comparison.php
  src/Carbon/Traits/Converter.php
  src/Carbon/Traits/Creator.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Difference.php
  src/Carbon/Traits/Localization.php
  src/Carbon/Traits/Modifiers.php
  src/Carbon/Traits/Options.php
  src/Carbon/Traits/Serialization.php
  src/Carbon/Traits/Test.php
  src/Carbon/Traits/Timestamp.php
  tests/Carbon/CreateTest.php
  tests/Carbon/DiffTest.php
  tests/Carbon/LocalizationTest.php
  tests/Carbon/StringsTest.php
  tests/CarbonImmutable/CreateTest.php
  tests/CarbonImmutable/DiffTest.php
  tests/CarbonImmutable/LocalizationTest.php
  tests/CarbonImmutable/StringsTest.php
  tests/CarbonPeriod/SettersTest.php
  tests/Jenssegers/DateTest.php
  tests/Jenssegers/JenssegersDate.php
  tests/Jenssegers/TestCaseBase.php
  tests/Jenssegers/TranslationElTest.php
  tests/Jenssegers/TranslationHuTest.php
  tests/Jenssegers/TranslationJaTest.php
  tests/Jenssegers/TranslationKaTest.php
  tests/Jenssegers/TranslationTaTest.php
  tests/Jenssegers/TranslationTest.php
  tests/Jenssegers/TranslationThTest.php
  tests/Localization/LocalizationTestCase.php
  tests/Localization/NlTest.php
Labels: enhancement

#1655 Document 2.16
  carbon.css
  contribute/docs/index.html
  contribute/index.html
  contribute/translate/index.html
  contribute/translators/index.html
  docs/index.html
  docs/index.src.html
  history/index.html
  index.html
  languages.json
  reference/index.html
  template.src.html
  tools/check.php
  tools/config.php
  tools/generate.php
Labels: documentation

#1666 Fix #1664 Add ago/from now/before/after translations
  src/Carbon/Lang/tk_TM.php
  tests/Localization/TkTest.php
  tests/Localization/TkTmTest.php
Labels: translation

#1668 Fix #1665 Add Standard Moroccan Tamazight translations
  src/Carbon/Lang/zgh.php
  tests/Localization/ZghTest.php
Labels: translation

#1667 Fix createFromFormat() to match native implementation when using test now
  src/Carbon/Traits/Creator.php
  tests/Carbon/CreateFromFormatTest.php
  tests/Carbon/TestingAidsTest.php
  tests/CarbonImmutable/CreateFromFormatTest.php
  tests/CarbonImmutable/TestingAidsTest.php
Labels: enhancement
