Repository briannesbitt/Carbon, pull requests merged in 2019-12, with the labels that each got.

#1952 Fix #1951 createFromTimestamp in DST chnge
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Timestamp.php
  tests/Carbon/CreateFromTimestampTest.php
  tests/CarbonImmutable/CreateFromTimestampTest.php
  tests/CarbonPeriod/CreateTest.php
Labels: bug

#1956 Fix #1953 Align Korean translation on CLDR
  src/Carbon/Lang/ko.php
  tests/Localization/KoKpTest.php
  tests/Localization/KoKrTest.php
  tests/Localization/KoTest.php
Labels: enhancement, translation

#1957 Fix #1954 Improvement from-now Armenian translation
  src/Carbon/Lang/hy.php
  tests/Localization/HyAmTest.php
  tests/Localization/HyTest.php
Labels: translation

#1959 Fix #1958 Standardize integer timezone input
  src/Carbon/Carbon.php
  src/Carbon/CarbonImmutable.php
  src/Carbon/CarbonInterface.php
  src/Carbon/Traits/Creator.php
  src/Carbon/Traits/Date.php
  tests/Carbon/ConstructTest.php
  tests/CarbonImmutable/CreateTest.php
Labels: enhancement

#1972 Use CarbonInterface instead of self for Date trait constant as keys
  composer.json
  phpmd.xml
  phpstan.neon
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/Exceptions/NotLocaleAwareException.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Localization.php
  tests/Carbon/IsTest.php
  tests/Carbon/LocalizationTest.php
  tests/CarbonImmutable/IsTest.php
  tests/CarbonImmutable/LocalizationTest.php
  tests/CarbonInterval/ForHumansTest.php
Labels: enhancement

#1971 Speed up resetMessages
  src/Carbon/Translator.php
Labels: enhancement
