Repository briannesbitt/Carbon, pull requests merged in 2019-07, with the labels that each got.

#1769 Implement #1768 Allow strings and DateTime instances in between()
  .travis.yml
  src/Carbon/Traits/Comparison.php
  tests/Carbon/ComparisonTest.php
  tests/CarbonImmutable/ComparisonTest.php
Labels: enhancement

#1771 Fix #1764 Filipino translations
  src/Carbon/Lang/fil_PH.php
  tests/Localization/FilPhTest.php
  tests/Localization/FilTest.php
Labels: translation

#1779 Optimize Laravel booting
  src/Carbon/Laravel/ServiceProvider.php
  tests/Laravel/App.php
Labels: enhancement

#1778 Implement new methods on CarbonPeriod
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/Exceptions/NotAPeriodException.php
  tests/CarbonInterval/CloneTest.php
  tests/CarbonPeriod/CloneTest.php
  tests/CarbonPeriod/CreateTest.php
  tests/CarbonPeriod/IterationMethodsTest.php
Labels: enhancement

#1785 Add equalTo method to CarbonInterval.
  src/Carbon/CarbonInterval.php
  tests/CarbonInterval/ComparisonTest.php
Labels: enhancement

#1786 #1686 Add CLI program
  .php_cs.dist
  .travis.yml
  bin/carbon
  bin/carbon.bat
  composer.json
  phpdoc.php
  phpmd.xml
  phpstan.neon
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/Cli/Invoker.php
  src/Carbon/Lang/cy.php
  src/Carbon/Lang/ga.php
  src/Carbon/Lang/uk.php
  src/Carbon/Traits/Comparison.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Difference.php
  src/Carbon/Traits/Options.php
  src/Carbon/Traits/Test.php
  src/Carbon/Traits/Units.php
  src/Carbon/Traits/Week.php
  src/Carbon/Translator.php
  tests/AbstractTestCase.php
  tests/Carbon/ArraysTest.php
  tests/Carbon/CreateSafeTest.php
  tests/Carbon/GenericMacroTest.php
  tests/Carbon/GettersTest.php
  tests/Carbon/StringsTest.php
  tests/CarbonImmutable/ArraysTest.php
  tests/CarbonImmutable/CreateSafeTest.php
  tests/CarbonImmutable/GenericMacroTest.php
  tests/CarbonImmutable/StringsTest.php
  tests/CarbonInterval/TotalTest.php
  tests/CarbonPeriod/CreateTest.php
  tests/CarbonPeriod/IteratorTest.php
  tests/Localization/GaIeTest.php
  tests/Localization/GaTest.php
Labels: enhancement

#1791 Fix #1790 diffInSeconds/Microseconds calculation
  src/Carbon/Traits/Difference.php
  tests/Carbon/DiffTest.php
  tests/CarbonImmutable/DiffTest.php
Labels: bug

#1794 Add equalTo method to CarbonPeriod.
  src/Carbon/CarbonPeriod.php
  tests/CarbonPeriod/ComparisonTest.php
Labels: enhancement

#1798 Add notEqualTo to CarbonInterval and CarbonPeriod
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  tests/CarbonInterval/ComparisonTest.php
  tests/CarbonPeriod/ComparisonTest.php
Labels: enhancement

#1799 Correct day names in Pashto
  src/Carbon/Lang/ps.php
  tests/Localization/PsAfTest.php
  tests/Localization/PsTest.php
Labels: translation

#1804 Swedish short units
  src/Carbon/Lang/sv.php
  tests/Localization/SvAxTest.php
  tests/Localization/SvFiTest.php
  tests/Localization/SvSeTest.php
  tests/Localization/SvTest.php
Labels: translation

#1805 Fix #1802 Fix Catalan translations
  src/Carbon/Lang/ca.php
  tests/Localization/CaAdTest.php
  tests/Localization/CaEsTest.php
  tests/Localization/CaEsValenciaTest.php
  tests/Localization/CaFrTest.php
  tests/Localization/CaItTest.php
  tests/Localization/CaTest.php
Labels: translation

#1808 Allow mixins to be traits
  phpmd.xml
  phpstan.neon
  src/Carbon/CarbonInterface.php
  src/Carbon/Traits/Comparison.php
  src/Carbon/Traits/Macro.php
  tests/Carbon/Fixtures/FooBar.php
  tests/Carbon/MacroTest.php
  tests/CarbonImmutable/MacroTest.php
Labels: enhancement

#1809 Add betweenExcluded method and between methods for intervals
  src/Carbon/CarbonInterval.php
  src/Carbon/Traits/Comparison.php
  tests/Carbon/ComparisonTest.php
  tests/CarbonImmutable/ComparisonTest.php
  tests/CarbonInterval/ComparisonTest.php
Labels: enhancement

#1810 Document macros and 2.22
  carbon.css
  composer.json
  contribute/translators/index.html
  docs/index.html
  docs/index.src.html
  index.html
  reference/index.html
  reference/index.src.html
  tools/api-history.php
  tools/generate.php
  tools/methods.php
Labels: documentation

#1812 Fix #1811 implement a_unit for Polish
  src/Carbon/Lang/pl.php
  tests/Localization/PlPlTest.php
  tests/Localization/PlTest.php
Labels: translation

#1818 Persian language localization fixes
  src/Carbon/Lang/fa.php
  tests/Localization/FaAfTest.php
  tests/Localization/FaIrTest.php
  tests/Localization/FaTest.php
  tests/Localization/MznTest.php
  tests/Localization/UzArabTest.php
Labels: translation
