Repository briannesbitt/Carbon, pull requests merged in 2019-02, with the labels that each got.

#1583 Use list join in interval dump through period dump
  src/Carbon/CarbonPeriod.php
  src/Carbon/Lang/nl.php
  tests/CarbonPeriod/ToStringTest.php
  tests/Localization/NlTest.php
Labels: 2.x, enhancement, translation

#1585 Sk short units
  src/Carbon/Lang/sk.php
  tests/Localization/SkTest.php
Labels: 2.x, translation

#1588 Unit tests improvements
  .multi-tester.yml
  .travis.yml
  composer.json
  tests/AbstractTestCase.php
  tests/AbstractTestCaseWithOldNow.php
  tests/Carbon/AddMonthsTest.php
  tests/Carbon/ArraysTest.php
  tests/Carbon/CreateFromFormatTest.php
  tests/Carbon/CreateFromTimeStringTest.php
  tests/Carbon/CreateSafeTest.php
  tests/Carbon/CreateTest.php
  tests/Carbon/DiffTest.php
  tests/Carbon/GettersTest.php
  tests/Carbon/InstanceTest.php
  tests/Carbon/IsTest.php
  tests/Carbon/LastErrorTest.php
  tests/Carbon/LocalizationTest.php
  tests/Carbon/MacroTest.php
  tests/Carbon/ModifyTest.php
  tests/Carbon/PhpBug72338Test.php
  tests/Carbon/RoundTest.php
  tests/Carbon/SerializationTest.php
  tests/Carbon/SettersTest.php
  tests/Carbon/StartEndOfTest.php
  tests/Carbon/StrictModeTest.php
  tests/CarbonImmutable/AddMonthsTest.php
  tests/CarbonImmutable/ArraysTest.php
  tests/CarbonImmutable/CreateFromFormatTest.php
  tests/CarbonImmutable/CreateFromTimeStringTest.php
  tests/CarbonImmutable/CreateSafeTest.php
  tests/CarbonImmutable/CreateTest.php
  tests/CarbonImmutable/DiffTest.php
  tests/CarbonImmutable/GettersTest.php
  tests/CarbonImmutable/InstanceTest.php
  tests/CarbonImmutable/IsTest.php
  tests/CarbonImmutable/LastErrorTest.php
  tests/CarbonImmutable/LocalizationTest.php
  tests/CarbonImmutable/MacroTest.php
  tests/CarbonImmutable/PhpBug72338Test.php
  tests/CarbonImmutable/RoundTest.php
  tests/CarbonImmutable/SerializationTest.php
  tests/CarbonImmutable/SettersTest.php
  tests/CarbonInterval/AddTest.php
  tests/CarbonInterval/ConstructTest.php
  tests/CarbonInterval/ForHumansTest.php
  tests/CarbonInterval/FromStringTest.php
  tests/CarbonInterval/GettersTest.php
  tests/CarbonInterval/SettersTest.php
  tests/CarbonInterval/StrictModeTest.php
  tests/CarbonInterval/TotalTest.php
  tests/CarbonPeriod/AliasTest.php
  tests/CarbonPeriod/CreateTest.php
  tests/CarbonPeriod/FilterTest.php
  tests/CarbonPeriod/IteratorTest.php
  tests/CarbonPeriod/MacroTest.php
  tests/CarbonPeriod/SettersTest.php
  tests/CarbonPeriod/StrictModeTest.php
  tests/CarbonPeriod/ToArrayTest.php
  tests/CarbonTimeZone/ConversionsTest.php
  tests/CarbonTimeZone/CreateTest.php
Labels: 2.x, enhancement

#1590 Allow PHP 8
  .travis.yml
  composer.json
Labels: 2.x, enhancement

#1610 [Update] Occitan: Add aUnit option for translations
  src/Carbon/Lang/oc.php
Labels: translation

#1613 Document 2.14.0
  docs/index.html
  docs/index.src.html
  index.html
  reference/index.html
  tools/check.php
  tools/config.php
  tools/generate.php
Labels: documentation

#1619 Fix #1615 Work around PHP bug https://bugs.php.net/bug.php?id=75577
  src/Carbon/Traits/Creator.php
  tests/Carbon/CreateFromFormatTest.php
Labels: bug
