Repository briannesbitt/Carbon, pull requests merged in 2019-04, with the labels that each got.

#1684 Update Albanian (sq.php) locale
  src/Carbon/Lang/sq.php
Labels: translation

#1690 Fix floating point modulo in floatDiffInDays() when $hoursDiff is a float
  src/Carbon/Traits/Difference.php
  tests/Carbon/DiffTest.php
  tests/CarbonImmutable/DiffTest.php
Labels: bug

#1691 Implement __debugInfo() method to ease var_dump
  phpstan.neon
  src/Carbon/CarbonInterface.php
  src/Carbon/Factory.php
  src/Carbon/FactoryImmutable.php
  src/Carbon/Traits/Localization.php
  src/Carbon/Traits/Options.php
  src/Carbon/Translator.php
  tests/Carbon/ArraysTest.php
  tests/CarbonImmutable/ArraysTest.php
  tests/CarbonInterval/GettersTest.php
  tests/CarbonPeriod/ToArrayTest.php
Labels: enhancement
