Repository briannesbitt/Carbon, pull requests merged in 2019-10, with the labels that each got.

#1900 Document version 2.25
  contribute/docs/index.html
  contribute/translators/index.html
  docs/index.html
  docs/index.src.html
  index.html
  tools/config.php
Labels: documentation

#1904 Replace $this with CarbonInterface in PHPDoc
  phpdoc.php
  phpstan.neon
  src/Carbon/Carbon.php
  src/Carbon/CarbonImmutable.php
  src/Carbon/CarbonInterface.php
  src/Carbon/Traits/Date.php
Labels: enhancement

#1911 Fix #1910 seconds Serbo-Croatian translation
  src/Carbon/Lang/sh.php
  tests/Localization/ScrTest.php
  tests/Localization/ShTest.php
Labels: translation

#1912 #356 Add toDateTimeLocalString precision parameter
  src/Carbon/CarbonInterface.php
  src/Carbon/Factory.php
  src/Carbon/FactoryImmutable.php
  src/Carbon/Traits/Converter.php
  src/Carbon/Traits/Date.php
  tests/Carbon/StringsTest.php
Labels: enhancement

#1915 Fix typehint for static create methods (Fix #1914)
  phpdoc.php
  src/Carbon/Carbon.php
  src/Carbon/CarbonImmutable.php
Labels: documentation, enhancement
