Repository briannesbitt/Carbon, pull requests merged in 2020-08, with the labels that each got.

#2148 Make CarbonInterval::copy() preserve the invert flag
  composer.json
  src/Carbon/CarbonInterval.php
  tests/CarbonInterval/CascadeTest.php
  tests/CommonTraits/MacroContextNestingTest.php
  tests/PHPStan/FeaturesTest.php
  tests/PHPStan/MacroTest.php
Labels: bug

#2152 #2146 Add shortand for DateTimeInterface::RFC3339_EXTENDED
  src/Carbon/CarbonInterface.php
  src/Carbon/Traits/Converter.php
  tests/Carbon/StringsTest.php
  tests/CarbonImmutable/StringsTest.php
Labels: enhancement

#2155 #2119 Dedupe the dff methods set
  phpdoc.php
  phpstan.neon
  src/Carbon/CarbonInterface.php
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/Factory.php
  src/Carbon/FactoryImmutable.php
  src/Carbon/Laravel/ServiceProvider.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Difference.php
  src/Carbon/Traits/Localization.php
  src/Carbon/Traits/Modifiers.php
  src/Carbon/Traits/Options.php
  src/Carbon/Traits/Rounding.php
  src/Carbon/Traits/Timestamp.php
  src/Carbon/Traits/Units.php
  src/Carbon/Traits/Week.php
  src/Carbon/Translator.php
  tests/Carbon/CreateFromTimestampTest.php
  tests/Carbon/DiffTest.php
  tests/Carbon/Fixtures/NoLocaleTranslator.php
  tests/Carbon/IsTest.php
  tests/Carbon/LocalizationTest.php
  tests/Carbon/MacroTest.php
  tests/Carbon/ModifyTest.php
  tests/Carbon/RelativeTest.php
  tests/Carbon/SettersTest.php
  tests/CarbonImmutable/DiffTest.php
  tests/CarbonImmutable/LocalizationTest.php
  tests/CarbonImmutable/MacroTest.php
  tests/CarbonImmutable/ModifyTest.php
  tests/CarbonImmutable/RelativeTest.php
  tests/CarbonInterval/ComparisonTest.php
  tests/CarbonInterval/ConstructTest.php
  tests/CarbonInterval/FromStringTest.php
  tests/CarbonInterval/GettersTest.php
  tests/CarbonInterval/ParseFromLocaleTest.php
  tests/CarbonInterval/RoundingTest.php
  tests/CarbonInterval/SettersTest.php
  tests/CarbonInterval/SpecTest.php
  tests/CarbonInterval/ToPeriodTest.php
  tests/CarbonInterval/TotalTest.php
  tests/CarbonPeriod/AliasTest.php
  tests/CarbonPeriod/CreateTest.php
  tests/CarbonPeriod/ToArrayTest.php
Labels: enhancement

#2164 🌎 Fix Estonian date formats based on CLDR data
  src/Carbon/Lang/et.php
Labels: translation

#2166 🌎 #2154 Add Hebrew abbreviations
  src/Carbon/Lang/he.php
  tests/Localization/HeIlTest.php
  tests/Localization/HeTest.php
Labels: translation

#2167 🌎 #2150 Fix Asturian plural
  src/Carbon/Lang/ast.php
  src/Carbon/Lang/ast_ES.php
  tests/Localization/AstEsTest.php
  tests/Localization/AstTest.php
Labels: translation

#2168 Evaluation for support of Symfony 4.4 in Carbon 3
  composer.json
  src/Carbon/Translator.php
  tests/Carbon/Fixtures/NoLocaleTranslator.php
Labels: available on 3.x-dev
