Repository briannesbitt/Carbon, pull requests merged in 2020-01, with the labels that each got.

#1978 Fix #1977 Greek "ago" translation
  src/Carbon/Lang/el.php
  tests/Jenssegers/TranslationElTest.php
  tests/Localization/ElCyTest.php
  tests/Localization/ElGrTest.php
  tests/Localization/ElTest.php
Labels: translation

#1980 CarbonPeriod and CarbonImmutable not behaving similarly
  src/Carbon/CarbonPeriod.php
  src/Carbon/Traits/Creator.php
  src/Carbon/Traits/Localization.php
  tests/CarbonPeriod/ToStringTest.php
Labels: bug

#1990 Fix #1989 Allow local setter/getter macros
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Macro.php
  src/Carbon/Traits/Serialization.php
  tests/Carbon/MacroTest.php
Labels: enhancement

#1993 Fix #1988 Allow timezone_type, timezone, date to be modified before __construct
  src/Carbon/Traits/Creator.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/ObjectInitialisation.php
  src/Carbon/Traits/Options.php
  src/Carbon/Traits/Serialization.php
  tests/Carbon/SerializationTest.php
  tests/CarbonImmutable/SerializationTest.php
Labels: enhancement

#1986 Allow to construct Carbon instance from DateTimeInterface
  phpstan.neon
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/Traits/Creator.php
  tests/Carbon/ConstructTest.php
  tests/CarbonImmutable/ConstructTest.php
  tests/CarbonInterval/ConstructTest.php
  tests/CarbonPeriod/CreateTest.php
Labels: enhancement

#2003 Fix creation when timezone is wrong and strict mode off
  src/Carbon/Traits/Creator.php
  tests/Carbon/ConstructTest.php
  tests/CarbonImmutable/ConstructTest.php
Labels: bug

#2005 #2002 Fix CarbonInterval not honoring toStringFormat setting.
  src/Carbon/CarbonInterval.php
  tests/CarbonInterval/ToStringTest.php
Labels: enhancement
