Repository briannesbitt/Carbon, pull requests merged in 2020-05, with the labels that each got.

#2080 #2075 Mute fallback parse() error to throw only the original one
  src/Carbon/CarbonInterface.php
  src/Carbon/Traits/Creator.php
  tests/Carbon/DiffTest.php
Labels: enhancement

#2078 Georgian typo and grammar
  src/Carbon/Lang/ka.php
  tests/Localization/KaGeTest.php
  tests/Localization/KaTest.php
Labels: needs tests, translation

#2082 #2081 Fix Ukrainian parsing
  src/Carbon/Traits/Localization.php
  tests/Jenssegers/TranslationUkTest.php
Labels: bug

#2083 Fix #2076 Sinhala translations
  src/Carbon/Lang/si.php
  tests/Localization/SiLkTest.php
  tests/Localization/SiTest.php
Labels: translation

#2084 Document new specific Carbon Doctrine types
  composer.json
  contribute/translators/index.html
  index.html
  symfony/index.html
  symfony/index.src.html
  tools/api-history.php
Labels: documentation

#2088 Add php tag for syntax highlighting in README.md
  readme.md
Labels: documentation

#2090 Fix #1967 Add auto mode for start/end of week
  src/Carbon/CarbonInterface.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Options.php
  tests/Carbon/DayOfWeekModifiersTest.php
  tests/CarbonImmutable/DayOfWeekModifiersTest.php
Labels: enhancement

#2095 Make locale default to current global locale in parseFromLocale()
  src/Carbon/CarbonInterface.php
  src/Carbon/CarbonInterval.php
  src/Carbon/Factory.php
  src/Carbon/FactoryImmutable.php
  src/Carbon/Traits/Creator.php
  src/Carbon/Traits/Localization.php
  src/Carbon/Traits/Modifiers.php
  tests/Carbon/CreateTest.php
  tests/Carbon/ModifyTest.php
  tests/CarbonImmutable/CreateTest.php
Labels: enhancement

#2097 Document 2.35
  composer.json
  contribute/translators/index.html
  docs/index.html
  docs/index.src.html
  index.html
  reference/index.html
  releases.json
Labels: documentation
