Repository briannesbitt/Carbon, pull requests merged in 2020-07, with the labels that each got.

#2124 Document 2.36
  composer.json
  docs/index.html
  docs/index.src.html
  index.html
  reference/index.html
  tools/generate.php
Labels: documentation

#2130 Add constants for months (fixes #2127)
  src/Carbon/CarbonInterface.php
Labels: enhancement

#2131 Fix #2129 Improve Panjabi translation
  src/Carbon/Lang/pa.php
  tests/Localization/PaGuruTest.php
  tests/Localization/PaInTest.php
  tests/Localization/PaTest.php
Labels: translation

#2132 Fixing the wrong labels for Kurdish language
  src/Carbon/Lang/ku.php
  tests/Localization/KuTest.php
  tests/Localization/KuTrTest.php
Labels: translation

#2137 Fix #2135 Allow `setTestNow()` to take `false`
  src/Carbon/CarbonInterface.php
  src/Carbon/Factory.php
  src/Carbon/FactoryImmutable.php
  src/Carbon/Traits/Test.php
  tests/Carbon/TestingAidsTest.php
Labels: enhancement

#2139 Fix #2138 Implement standalone months for Lithuanian language
  src/Carbon/Lang/lt.php
Labels: translation

#2141 Accept DateTimeInterface in parse()
  src/Carbon/CarbonInterface.php
  src/Carbon/Traits/Creator.php
Labels: enhancement

#2142 Fix #2126 cascade() method
  .styleci.yml
  src/Carbon/CarbonInterval.php
  tests/Carbon/DiffTest.php
  tests/Carbon/LocalizationTest.php
  tests/CarbonImmutable/LocalizationTest.php
  tests/CarbonInterval/CascadeTest.php
  tests/CarbonInterval/CreateFromFormatTest.php
  tests/CarbonInterval/GettersTest.php
  tests/CarbonInterval/RoundingTest.php
  tests/CarbonInterval/SettersTest.php
  tests/CarbonInterval/TotalTest.php
Labels: bug

#2143 Document version 2.37.0
  composer.json
  contribute/translators/index.html
  docs/index.html
  index.html
  reference/index.html
  tools/check.php
Labels: documentation
