Repository briannesbitt/Carbon, pull requests merged in 2020-10, with the labels that each got.

#2205 Implement #2199 Create from/set microtime
  .gitignore
  src/Carbon/Carbon.php
  src/Carbon/CarbonImmutable.php
  src/Carbon/CarbonInterface.php
  src/Carbon/Factory.php
  src/Carbon/FactoryImmutable.php
  src/Carbon/Traits/Creator.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Timestamp.php
  tests/Carbon/CreateFromTimestampTest.php
  tests/Carbon/FluidSettersTest.php
  tests/Carbon/SettersTest.php
  tests/CarbonImmutable/CreateFromTimestampTest.php
  tests/CarbonImmutable/FluidSettersTest.php
Labels: enhancement

#2207 #2198 Add hasFormatWithModifiers() method
  src/Carbon/Traits/Comparison.php
  src/Carbon/Traits/Options.php
  tests/Carbon/IsTest.php
Labels: enhancement

#2208 #2194 Add readonly public properties to CarbonPeriod
  src/Carbon/CarbonPeriod.php
  tests/CarbonPeriod/AliasTest.php
  tests/CarbonPeriod/GettersTest.php
  tests/CarbonPeriod/IteratorTest.php
Labels: enhancement

#2213 Malay translation improvement
  src/Carbon/Lang/ms.php
  tests/Localization/MsBnTest.php
  tests/Localization/MsMyTest.php
  tests/Localization/MsSgTest.php
  tests/Localization/MsTest.php
Labels: translation

#2212 Fix #2209 Cover missed branches
  src/Carbon/Laravel/ServiceProvider.php
  tests/CarbonPeriod/FilterTest.php
  tests/CarbonPeriod/Fixtures/AbstractCarbon.php
  tests/CarbonPeriod/SettersTest.php
  tests/Language/TranslatorTest.php
  tests/Laravel/App.php
  tests/Laravel/ServiceProviderTest.php
Labels: enhancement

#2211 Document 2.41
  composer.json
  contribute/translators/index.html
  docs/index.html
  docs/index.src.html
  index.html
  reference/index.html
  releases.json
  tools/check.php
  tools/methods.php
Labels: documentation

#2219 Fix #2214 YYYYMMDD support for parse()
  src/Carbon/Traits/Creator.php
  tests/Carbon/ConstructTest.php
  tests/CarbonImmutable/ConstructTest.php
Labels: bug

#2225 Improve Zend optimization with native_function_invocation
  .php_cs.dist
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/CarbonTimeZone.php
  src/Carbon/Exceptions/NotLocaleAwareException.php
  src/Carbon/Factory.php
  src/Carbon/Lang/cy.php
  src/Carbon/PHPStan/Macro.php
  src/Carbon/PHPStan/MacroScanner.php
  src/Carbon/Traits/Comparison.php
  src/Carbon/Traits/Converter.php
  src/Carbon/Traits/Creator.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Difference.php
  src/Carbon/Traits/IntervalRounding.php
  src/Carbon/Traits/Localization.php
  src/Carbon/Traits/Mixin.php
  src/Carbon/Traits/Modifiers.php
  src/Carbon/Traits/Options.php
  src/Carbon/Traits/Rounding.php
  src/Carbon/Traits/Serialization.php
  src/Carbon/Traits/Test.php
  src/Carbon/Traits/Timestamp.php
  src/Carbon/Traits/Units.php
  src/Carbon/Translator.php
Labels: enhancement
