Repository briannesbitt/Carbon, pull requests merged in 2020-06, with the labels that each got.

#2102 Fix #2101 iterate over every timezone to find it
  src/Carbon/CarbonTimeZone.php
  tests/CarbonTimeZone/ConversionsTest.php
Labels: enhancement

#2115 Add microsecond as possible diff minimum unit
  src/Carbon/CarbonInterval.php
  src/Carbon/Lang/de.php
  src/Carbon/Lang/en.php
  src/Carbon/Lang/es.php
  src/Carbon/Lang/fr.php
  src/Carbon/Lang/it.php
  src/Carbon/Lang/pt.php
  tests/CarbonInterval/ForHumansTest.php
Labels: enhancement

#2116 Implement dynamic intervals
  composer.json
  phpdoc.php
  phpstan.neon
  src/Carbon/Carbon.php
  src/Carbon/CarbonConverterInterface.php
  src/Carbon/CarbonImmutable.php
  src/Carbon/CarbonInterface.php
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/Traits/IntervalStep.php
  src/Carbon/Traits/Units.php
  tests/Carbon/AddTest.php
  tests/Carbon/SubTest.php
  tests/CarbonImmutable/AddTest.php
  tests/CarbonImmutable/SubTest.php
  tests/CarbonInterval/AddTest.php
  tests/CarbonPeriod/DynamicIntervalTest.php
  tests/Fixtures/dynamicInterval.php
Labels: enhancement

#2118 Revert Doctrine default precision change
  src/Carbon/Doctrine/CarbonTypeConverter.php
  tests/Doctrine/CarbonTypesTest.php
Labels: bug

#2107 Fix #2106 Add full somali locale
  src/Carbon/Lang/so.php
  src/Carbon/Lang/so_DJ.php
  src/Carbon/Lang/so_ET.php
  src/Carbon/Lang/so_KE.php
  src/Carbon/Lang/so_SO.php
  tests/Localization/SoDjTest.php
  tests/Localization/SoEtTest.php
  tests/Localization/SoKeTest.php
  tests/Localization/SoSoTest.php
  tests/Localization/SoTest.php
Labels: translation

#1916 Add PHPStan extension for macros
  .travis.yml
  composer.json
  extension.neon
  phpstan.neon
  phpunit.xml.dist
  src/Carbon/CarbonInterface.php
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/PHPStan/Macro.php
  src/Carbon/PHPStan/MacroExtension.php
  src/Carbon/PHPStan/MacroScanner.php
  src/Carbon/Traits/Creator.php
  src/Carbon/Traits/Localization.php
  src/Carbon/Traits/Macro.php
  src/Carbon/Traits/Mixin.php
  src/Carbon/Traits/Modifiers.php
  src/Carbon/Traits/Serialization.php
  src/Carbon/Traits/Week.php
  tests/CarbonInterval/ForHumansTest.php
  tests/CarbonInterval/SettersTest.php
  tests/PHPStan/BadFixture.php
  tests/PHPStan/FeaturesTest.php
  tests/PHPStan/Fixture.php
  tests/PHPStan/MacroExtensionTest.php
  tests/PHPStan/MacroTest.php
Labels: enhancement, postponed
