Repository briannesbitt/Carbon, pull requests merged in 2020-02, with the labels that each got.

#2007 Fix #1651 weeks/days calculation in ->total()
  src/Carbon/CarbonInterval.php
  tests/CarbonInterval/TotalTest.php
Labels: bug

#2010 Update CarbonInterface.php
  src/Carbon/CarbonInterface.php
Labels: documentation

#2014 Implement #2012 ->betweenIncluded() method
  src/Carbon/CarbonInterface.php
  src/Carbon/CarbonInterval.php
  src/Carbon/Traits/Comparison.php
  tests/Carbon/ComparisonTest.php
  tests/CarbonInterval/ComparisonTest.php
Labels: documentation, enhancement

#2013 Improve translation using CLDR comparison
  src/Carbon/CarbonInterface.php
  src/Carbon/CarbonInterval.php
  src/Carbon/Lang/cs.php
  src/Carbon/Traits/Boundaries.php
  tests/Carbon/StringsTest.php
  tests/CarbonImmutable/StringsTest.php
  tests/Localization/DeAtTest.php
  tests/Localization/DeBeTest.php
  tests/Localization/DeChTest.php
  tests/Localization/DeDeTest.php
  tests/Localization/DeItTest.php
  tests/Localization/DeLiTest.php
  tests/Localization/DeLuTest.php
  tests/Localization/DeTest.php
  tests/Localization/EtEeTest.php
  tests/Localization/EtTest.php
  tests/Localization/FiFiTest.php
  tests/Localization/FiTest.php
  tests/Localization/LtLtTest.php
  tests/Localization/LtTest.php
  tests/Localization/MeTest.php
  tests/Localization/MnMnTest.php
  tests/Localization/MnTest.php
  tests/Localization/SrCyrlBaTest.php
  tests/Localization/SrCyrlMeTest.php
  tests/Localization/SrCyrlTest.php
  tests/Localization/SrCyrlXkTest.php
  tests/Localization/SrLatnBaTest.php
  tests/Localization/SrLatnMeTest.php
  tests/Localization/SrLatnTest.php
  tests/Localization/SrLatnXkTest.php
  tests/Localization/SrMeTest.php
  tests/Localization/SrRsLatinTest.php
  tests/Localization/SrRsTest.php
  tests/Localization/SrTest.php
Labels: enhancement, translation

#2019 always use non-deprecated translation method
  src/Carbon/Traits/Localization.php
Labels: enhancement

#2020 Remove deprecated method
  tests/CarbonPeriod/CreateTest.php
Labels: enhancement

#2021 Skip test when an English locale is unavailable
  tests/Carbon/CreateFromTimestampTest.php
  tests/CarbonImmutable/CreateFromTimestampTest.php
  tests/Language/TranslatorTest.php
Labels: enhancement

#2023 Add method for diffInQuarters
  src/Carbon/CarbonInterface.php
  src/Carbon/Traits/Difference.php
  tests/Carbon/DiffTest.php
Labels: enhancement

#2026 Fix #2025 Use date months for LL+ ISO formats
  src/Carbon/Lang/be.php
  src/Carbon/Lang/ca.php
  src/Carbon/Lang/el.php
  src/Carbon/Lang/hr.php
  src/Carbon/Lang/hy.php
  src/Carbon/Lang/ka.php
  src/Carbon/Lang/pl.php
  src/Carbon/Lang/ru.php
  src/Carbon/Lang/uk.php
  tests/Carbon/ComparisonTest.php
  tests/Carbon/LocalizationTest.php
  tests/CarbonImmutable/ComparisonTest.php
  tests/Jenssegers/DateTest.php
  tests/Jenssegers/TranslationElTest.php
  tests/Jenssegers/TranslationHuTest.php
Labels: bug

#2028 Fix #2027 Catalan short months declension
  src/Carbon/Lang/ca.php
Labels: translation
