Repository briannesbitt/Carbon, pull requests merged in 2020-09, with the labels that each got.

#2181 Fix #2180 hasFormat() with slashes
  src/Carbon/Traits/Comparison.php
  src/Carbon/Traits/Options.php
  tests/Carbon/IsTest.php
  tests/CarbonImmutable/IsTest.php
Labels: bug

#2182 Fix #2177 auto-fill timezone argument in factory methods
  src/Carbon/Factory.php
  tests/Factory/FactoryTest.php
Labels: bug

#2183 Fix #2175 Add floatDiffInWeeks() method
  src/Carbon/CarbonInterface.php
  src/Carbon/Factory.php
  src/Carbon/FactoryImmutable.php
  src/Carbon/Traits/Difference.php
  tests/Carbon/DiffTest.php
  tests/CarbonImmutable/DiffTest.php
Labels: enhancement

#2188 Fix #2187 Luxembourgish translations
  src/Carbon/Lang/lb.php
  tests/Localization/LbLuTest.php
  tests/Localization/LbTest.php
Labels: translation

#2186 Edit language for Greenlandic
  src/Carbon/Lang/kl_GL.php
  tests/Localization/KlGlTest.php
  tests/Localization/KlTest.php
Labels: enhancement, translation

#2196 Fix #2195 Norwegian Nynorsk nn_NO translations
  src/Carbon/Lang/nn.php
  tests/Localization/NnNoTest.php
  tests/Localization/NnTest.php
  tests/Localization/NnhTest.php
Labels: translation

#2197 Allow Carbon::createFromFormat('c')
  src/Carbon/Traits/Creator.php
  tests/Carbon/CreateFromFormatTest.php
Labels: php bug

#2203 Fix #2201 Add date and timezone in debug info only when ready
  src/Carbon/Traits/Options.php
  tests/Carbon/ArraysTest.php
  tests/Carbon/Fixtures/DumpCarbon.php
Labels: php bug
