Repository briannesbitt/Carbon, pull requests merged in 2020-04, with the labels that each got.

#2055 Typo in example of phpdoc
  src/Carbon/Traits/Comparison.php
Labels: documentation

#2056 Add ext-mbstring to requirements
  composer.json
Labels: enhancement

#2060 #2058 Diff for humans milliseconds
  src/Carbon/CarbonInterval.php
  src/Carbon/Lang/de.php
  src/Carbon/Lang/en.php
  src/Carbon/Lang/es.php
  src/Carbon/Lang/fr.php
  src/Carbon/Lang/it.php
  tests/CarbonInterval/ForHumansTest.php
Labels: enhancement

#2062 Fix #2059 timezone offset name for not full hour
  src/Carbon/CarbonTimeZone.php
  tests/CarbonTimeZone/ConversionsTest.php
Labels: bug, enhancement

#2063 Provide util methods to get CarbonTimeZone objects or offset string from hour/minutes shift number
  phpunit.xml.dist
  src/Carbon/CarbonTimeZone.php
  src/Carbon/Translator.php
  tests/CarbonTimeZone/ConversionsTest.php
  tests/Language/TranslatorTest.php
Labels: enhancement

#2069 Fix static analyses of Carbon
  src/Carbon/Traits/Rounding.php
Labels: documentation

#2068 Document 2.33
  composer.json
  contribute/translators/index.html
  docs/index.html
  docs/index.src.html
  index.html
  reference/index.html
  releases.json
  tools/api-history.php
Labels: documentation
