Repository briannesbitt/Carbon, pull requests merged in 2020-03, with the labels that each got.

#2030 Fix #2022 Handle absolute diff translation declensions
  src/Carbon/CarbonInterval.php
  tests/Carbon/LocalizationTest.php
  tests/CarbonImmutable/LocalizationTest.php
  tests/Localization/BeByLatinTest.php
  tests/Localization/BeByTest.php
  tests/Localization/BeTest.php
  tests/Localization/HuHuTest.php
  tests/Localization/HuTest.php
Labels: translation

#2015 Document 2.31
  composer.json
  docs/index.html
  docs/index.src.html
  index.html
  reference/index.html
Labels: documentation

#2029 Start MySQL in Laravel unit tests
  .travis.yml
Labels: enhancement

#2037 Fix #2036 Short month January translation in de_AT
  src/Carbon/Lang/de_AT.php
Labels: translation

#2042 #2041 Provide Doctrine ORM Carbon types
  composer.json
  phpunit.xml.dist
  src/Carbon/Doctrine/CarbonType.php
  src/Carbon/Doctrine/DateTimeDefaultPrecision.php
  src/Carbon/Doctrine/DateTimeImmutableType.php
  src/Carbon/Doctrine/DateTimeType.php
  tests/Carbon/SettersTest.php
Labels: enhancement

#2045 Fix doctrine orm carbon type
  src/Carbon/Doctrine/CarbonType.php
Labels: bug

#2049 Fix doctrine ORM Carbon type inheritance
  src/Carbon/Doctrine/DateTimeImmutableType.php
  src/Carbon/Doctrine/DateTimeType.php
Labels: bug

#2046 Update uz.php
  src/Carbon/Lang/uz.php
Labels: needs tests, translation

#2052 Update uz.php (#2046)
  src/Carbon/Lang/uz.php
  src/Carbon/Traits/Units.php
  tests/Localization/UzCyrlTest.php
  tests/Localization/UzTest.php
  tests/Localization/UzUzCyrillicTest.php
Labels: needs tests, translation
