Repository briannesbitt/Carbon, pull requests merged in 2021-06, with the labels that each got.

#2346 Drop fixes for old PHP versions
  src/Carbon/CarbonInterval.php
  src/Carbon/Traits/Creator.php
  src/Carbon/Traits/Units.php
Labels: enhancement

#2347 Support decimal numbers in addRealUnit
  src/Carbon/CarbonInterface.php
  src/Carbon/Factory.php
  src/Carbon/FactoryImmutable.php
  src/Carbon/Traits/Units.php
Labels: enhancement

#2349 Fix polish translation causing a runtime error
  src/Carbon/Lang/pl.php
Labels: bug, translation

#2351 Add avoidMutation() method to copy an instance only if mutable
  .github/workflows/tests.yml
  src/Carbon/CarbonImmutable.php
  src/Carbon/CarbonInterface.php
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/Traits/Comparison.php
  src/Carbon/Traits/Converter.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Difference.php
  src/Carbon/Traits/IntervalStep.php
  src/Carbon/Traits/Modifiers.php
  src/Carbon/Traits/Rounding.php
  src/Carbon/Traits/Units.php
  src/Carbon/Traits/Week.php
Labels: enhancement

#2353 Use the return value from callback in withTestNow
  src/Carbon/Traits/Test.php
  tests/Carbon/TestingAidsTest.php
  tests/CarbonImmutable/TestingAidsTest.php
Labels: enhancement

#2362 Add space into diffForHumans modifier
  docs/index.src.html
Labels: documentation

#2365 Fix nullable types
  src/Carbon/Factory.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Localization.php
  src/Carbon/Traits/Week.php
  tests/Carbon/LocalizationTest.php
  tests/CarbonImmutable/LocalizationTest.php
Labels: enhancement

#2369 Fix #2368 pad left trailing zeros in createFromTimestamp()
  src/Carbon/Traits/Timestamp.php
  tests/CarbonImmutable/CreateFromTimestampTest.php
Labels: bug
