Repository briannesbitt/Carbon, pull requests merged in 2021-02, with the labels that each got.

#2275 Filter UnknownGetterException from getSettings
  src/Carbon/CarbonPeriod.php
  src/Carbon/Traits/Options.php
  tests/CarbonPeriod/GettersTest.php
Labels: enhancement

#2274 Fix #2091 Latvian updates
  src/Carbon/Lang/lv.php
  tests/Localization/LvLvTest.php
  tests/Localization/LvTest.php
Labels: translation

#2279 Document behavior difference with null passed in add/sub method
  .github/workflows/tests.yml
  .travis.yml
  docs/index.html
  docs/index.src.html
Labels: documentation

#2281 Add plus() and minus() methods to CarbonInterval
  src/Carbon/CarbonInterval.php
  tests/AbstractTestCase.php
  tests/CarbonInterval/AddTest.php
  tests/Laravel/App.php
Labels: enhancement

#2282 Add type hints in CarbonInterval
  phpstan.neon
  src/Carbon/CarbonInterval.php
  src/Carbon/Traits/Creator.php
  tests/Carbon/CreateFromFormatTest.php
  tests/Carbon/DiffTest.php
  tests/Carbon/IsTest.php
  tests/CarbonImmutable/IsTest.php
Labels: enhancement

#2284 Upgrade to PHPUnit 9
  .github/workflows/tests.yml
  composer.json
  phpunit.xml.dist
Labels: enhancement

#2283 Make CarbonPeriod extends DatePeriod
  src/Carbon/CarbonPeriod.php
  src/Carbon/Traits/Options.php
  tests/Carbon/ConstructTest.php
  tests/Carbon/ObjectsTest.php
  tests/CarbonImmutable/ConstructTest.php
  tests/CarbonInterval/ConstructTest.php
  tests/CarbonPeriod/CreateTest.php
  tests/CarbonTimeZone/CreateTest.php
Labels: enhancement, postponed

#2287 Use finest overflow detection
  src/Carbon/Traits/Rounding.php
  tests/Carbon/RoundTest.php
  tests/CarbonImmutable/RoundTest.php
Labels: bug

#2288 Makes PHPDoc consistent
  src/Carbon/Traits/Creator.php
Labels: documentation

#2293 Properly fallback static macro if errors are not converted into exceptions
  src/Carbon/Traits/Mixin.php
Labels: enhancement
