Repository briannesbitt/Carbon, pull requests merged in 2021-05, with the labels that each got.

#2325 Allow endless periods
  src/Carbon/CarbonImmutable.php
  src/Carbon/CarbonInterface.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/Traits/Comparison.php
  tests/CarbonPeriod/GettersTest.php
  tests/CarbonPeriod/RoundingTest.php
  tests/Jenssegers/DateTest.php
Labels: enhancement

#2327 Fix #2326 handle p format in canBeCreatedFromFormat()
  src/Carbon/Traits/Options.php
  tests/Carbon/IsTest.php
Labels: bug

#2328 Update et.php - Add abbreviations
  src/Carbon/Lang/et.php
  tests/Localization/EtEeTest.php
  tests/Localization/EtTest.php
Labels: needs tests, translation

#2336 Fix Belarusian translation
  src/Carbon/Lang/be.php
  tests/Localization/BeByTest.php
  tests/Localization/BeTest.php
Labels: translation

#2332 Add instantiation method Carbon::createStrict()
  src/Carbon/Traits/Creator.php
  tests/Carbon/CreateStrictTest.php
Labels: enhancement

#2340 Return null instead of false
  phpdoc.php
  src/Carbon/Carbon.php
  src/Carbon/CarbonImmutable.php
  src/Carbon/CarbonInterface.php
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonTimeZone.php
  src/Carbon/Factory.php
  src/Carbon/FactoryImmutable.php
  src/Carbon/Traits/Creator.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Difference.php
  src/Carbon/Traits/Options.php
  src/Carbon/Traits/Week.php
  tests/Carbon/CreateSafeTest.php
  tests/Carbon/CreateStrictTest.php
  tests/Carbon/CreateTest.php
  tests/Carbon/SettersTest.php
  tests/Carbon/StrictModeTest.php
  tests/CarbonTimeZone/ConversionsTest.php
Labels: enhancement
