Repository briannesbitt/Carbon, pull requests merged in 2022-04, with the labels that each got.

#2577 Always use strict in_array comparison.
  build.php
  src/Carbon/CarbonInterval.php
  src/Carbon/Lang/cy.php
  src/Carbon/Traits/Comparison.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Units.php
  tests/CarbonPeriod/MacroTest.php
  tests/Localization/LanguagesCoverageTest.php
Labels: enhancement

#2583 Take minimum value for rounding
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Rounding.php
  tests/Carbon/RoundTest.php
  tests/CarbonInterval/ForHumansTest.php
Labels: bug

#2571 add kurdish (sorani) language
  src/Carbon/Lang/ckb.php
  tests/Localization/CkbTest.php
Labels: translation

#2585 [Danish] Weekday and month abbreviations + ‘ago’
  src/Carbon/Lang/da.php
  tests/Localization/DaDkTest.php
  tests/Localization/DaGlTest.php
  tests/Localization/DaTest.php
Labels: translation

#2578 Add property getters for exceptions
  src/Carbon/Exceptions/BadComparisonUnitException.php
  src/Carbon/Exceptions/BadFluentConstructorException.php
  src/Carbon/Exceptions/BadFluentSetterException.php
  src/Carbon/Exceptions/BadMethodCallException.php
  src/Carbon/Exceptions/Exception.php
  src/Carbon/Exceptions/ImmutableException.php
  src/Carbon/Exceptions/InvalidArgumentException.php
  src/Carbon/Exceptions/InvalidCastException.php
  src/Carbon/Exceptions/InvalidDateException.php
  src/Carbon/Exceptions/InvalidFormatException.php
  src/Carbon/Exceptions/InvalidIntervalException.php
  src/Carbon/Exceptions/InvalidPeriodDateException.php
  src/Carbon/Exceptions/InvalidPeriodParameterException.php
  src/Carbon/Exceptions/InvalidTimeZoneException.php
  src/Carbon/Exceptions/InvalidTypeException.php
  src/Carbon/Exceptions/NotACarbonClassException.php
  src/Carbon/Exceptions/NotAPeriodException.php
  src/Carbon/Exceptions/NotLocaleAwareException.php
  src/Carbon/Exceptions/OutOfRangeException.php
  src/Carbon/Exceptions/ParseErrorException.php
  src/Carbon/Exceptions/RuntimeException.php
  src/Carbon/Exceptions/UnitException.php
  src/Carbon/Exceptions/UnitNotConfiguredException.php
  src/Carbon/Exceptions/UnknownGetterException.php
  src/Carbon/Exceptions/UnknownMethodException.php
  src/Carbon/Exceptions/UnknownSetterException.php
  src/Carbon/Exceptions/UnknownUnitException.php
  src/Carbon/Exceptions/UnreachableException.php
  tests/Carbon/Exceptions/BadComparisonUnitExceptionTest.php
  tests/Carbon/Exceptions/BadFluentConstructorExceptionTest.php
  tests/Carbon/Exceptions/BadFluentSetterExceptionTest.php
  tests/Carbon/Exceptions/ImmutableExceptionTest.php
  tests/Carbon/Exceptions/NotACarbonClassExceptionTest.php
  tests/Carbon/Exceptions/ParseErrorExceptionTest.php
  tests/Carbon/Exceptions/UnitNotConfiguredExceptionTest.php
  tests/Carbon/Exceptions/UnknownGetterExceptionTest.php
  tests/Carbon/Exceptions/UnknownMethodExceptionTest.php
  tests/Carbon/Exceptions/UnknownSetterExceptionTest.php
  tests/Carbon/Exceptions/UnknownUnitExceptionTest.php
Labels: enhancement

#2589 Allow plus prefix for numeric timezone
  src/Carbon/CarbonTimeZone.php
  tests/CarbonTimeZone/CreateTest.php
Labels: bug
