Repository briannesbitt/Carbon, pull requests merged in 2022-10, with the labels that each got.

#2677 Print original params in Carbon\Traits\Units::addUnit error message
  src/Carbon/Traits/Units.php
Labels: enhancement

#2682 Added case 'yr', 'yrs' and 'mos' alias in CarbonInterval string parser
  src/Carbon/CarbonInterval.php
Labels: enhancement

#2683 Allow lowercase macro-format per-language customization
  src/Carbon/Lang/fi.php
  src/Carbon/Traits/Date.php
Labels: translation

#2689 Update SL language ("2 years ago" translation)
  src/Carbon/Lang/sl.php
  tests/Localization/SlSiTest.php
  tests/Localization/SlTest.php
Labels: translation

#2693 Translate ordinal word when parsing string
  src/Carbon/Lang/de.php
  src/Carbon/Lang/es.php
  src/Carbon/Lang/fr.php
  src/Carbon/Lang/it.php
  src/Carbon/Lang/pt.php
  src/Carbon/Traits/Localization.php
  tests/Jenssegers/DateTest.php
Labels: enhancement, translation

#2688 Fix PHPStan macro arguments check
  .github/workflows/tests.yml
  lazy/Carbon/PHPStan/AbstractMacroBuiltin.php
  lazy/Carbon/PHPStan/AbstractMacroStatic.php
  lazy/Carbon/PHPStan/MacroStrongType.php
  lazy/Carbon/PHPStan/MacroWeakType.php
  src/Carbon/PHPStan/AbstractMacro.php
  tests/PHPStan/Fixture.php
  tests/PHPStan/MacroExtensionTest.php
  tests/PHPStan/MacroTest.php
  tests/PHPStan/bootstrap-non-static.php
  tests/PHPStan/bootstrap.php
Labels: bug
