Repository briannesbitt/Carbon, pull requests merged in 2022-09, with the labels that each got.

#2663 Fix PHP 8.2 issue with false for lastErrors
  src/Carbon/Traits/Creator.php
  tests/Carbon/LastErrorTest.php
  tests/CarbonImmutable/LastErrorTest.php
Labels: php bug

#2665 Prevent floor overflow
  src/Carbon/Traits/Rounding.php
  tests/Carbon/RoundTest.php
Labels: bug

#2667 Prevent ceil precision loss
  src/Carbon/Traits/Rounding.php
  tests/Carbon/RoundTest.php
Labels: bug

#2669 Harmonize toStringFormat config
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/Traits/Converter.php
  src/Carbon/Traits/ToStringFormat.php
  tests/CarbonInterval/ToStringTest.php
  tests/CarbonPeriod/ToStringTest.php
Labels: enhancement

#2670 Distinguish months and months_standalone in Latvian
  src/Carbon/Lang/lv.php
Labels: translation
