Repository briannesbitt/Carbon, pull requests merged in 2023-01, with the labels that each got.

#2740 Fix Serbian pluralization
  lazy/Carbon/MessageFormatter/MessageFormatterMapperStrongType.php
  lazy/Carbon/MessageFormatter/MessageFormatterMapperWeakType.php
  phpstan.neon
  src/Carbon/AbstractTranslator.php
  src/Carbon/Lang/be.php
  src/Carbon/Lang/ca_ES_Valencia.php
  src/Carbon/Lang/oc.php
  src/Carbon/Lang/sh.php
  src/Carbon/Lang/sr_Cyrl.php
  src/Carbon/Lang/sr_Cyrl_BA.php
  src/Carbon/Lang/sr_Cyrl_ME.php
  src/Carbon/Lang/sr_Cyrl_XK.php
  src/Carbon/Lang/sr_Latn_BA.php
  src/Carbon/Lang/sr_Latn_ME.php
  src/Carbon/Lang/sr_Latn_XK.php
  src/Carbon/MessageFormatter/MessageFormatterMapper.php
  tests/Carbon/LocalizationTest.php
  tests/CarbonImmutable/LocalizationTest.php
  tests/Localization/CaEsValenciaTest.php
  tests/Localization/MeTest.php
  tests/Localization/SrLatnBaTest.php
  tests/Localization/SrLatnMeTest.php
  tests/Localization/SrLatnXkTest.php
Labels: translation

#2742 Updated Polish translation
  src/Carbon/Lang/pl.php
Labels: translation

#2745 Enforce $skip array type
  src/Carbon/Traits/Difference.php
  tests/Carbon/DiffTest.php
Labels: bug

#2750 Add isLongIsoYear() method
  src/Carbon/Traits/Comparison.php
  tests/Carbon/GettersTest.php
  tests/CarbonInterval/RoundingTest.php
Labels: enhancement

#2752 Fix is() output when giving a month name only
  src/Carbon/Traits/Comparison.php
  tests/CarbonImmutable/IsTest.php
Labels: bug

#2760 Added eastern Arabic numerals to all locales of the Mashriq countries
  src/Carbon/Lang/ar_AE.php
  src/Carbon/Lang/ar_BH.php
  src/Carbon/Lang/ar_EG.php
  src/Carbon/Lang/ar_IQ.php
  src/Carbon/Lang/ar_JO.php
  src/Carbon/Lang/ar_KW.php
  src/Carbon/Lang/ar_LB.php
  src/Carbon/Lang/ar_OM.php
  src/Carbon/Lang/ar_PS.php
  src/Carbon/Lang/ar_QA.php
  src/Carbon/Lang/ar_SA.php
  src/Carbon/Lang/ar_SD.php
  src/Carbon/Lang/ar_SY.php
  src/Carbon/Lang/ar_YE.php
Labels: translation

#2761 Add CarbonPeriodImmutable class
  src/Carbon/CarbonInterval.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/CarbonPeriodImmutable.php
  src/Carbon/Traits/Converter.php
  src/Carbon/Traits/Options.php
  tests/AbstractTestCase.php
  tests/CarbonPeriod/AliasTest.php
  tests/CarbonPeriod/CloneTest.php
  tests/CarbonPeriod/ComparisonTest.php
  tests/CarbonPeriod/CreateTest.php
  tests/CarbonPeriod/DynamicIntervalTest.php
  tests/CarbonPeriod/FilterTest.php
  tests/CarbonPeriod/Fixtures/CarbonPeriodFactory.php
  tests/CarbonPeriod/GettersTest.php
  tests/CarbonPeriod/IteratorTest.php
  tests/CarbonPeriod/MacroTest.php
  tests/CarbonPeriod/RoundingTest.php
  tests/CarbonPeriod/SettersTest.php
  tests/CarbonPeriod/StrictModeTest.php
  tests/CarbonPeriod/ToArrayTest.php
  tests/CarbonPeriod/ToDatePeriodTest.php
  tests/CarbonPeriod/ToStringTest.php
  tests/CarbonPeriodImmutable/AliasTest.php
  tests/CarbonPeriodImmutable/CloneTest.php
  tests/CarbonPeriodImmutable/ComparisonTest.php
  tests/CarbonPeriodImmutable/CreateTest.php
  tests/CarbonPeriodImmutable/DynamicIntervalTest.php
  tests/CarbonPeriodImmutable/FilterTest.php
  tests/CarbonPeriodImmutable/GettersTest.php
  tests/CarbonPeriodImmutable/IterationMethodsTest.php
  tests/CarbonPeriodImmutable/IteratorTest.php
  tests/CarbonPeriodImmutable/MacroTest.php
  tests/CarbonPeriodImmutable/RoundingTest.php
  tests/CarbonPeriodImmutable/SettersTest.php
  tests/CarbonPeriodImmutable/StrictModeTest.php
  tests/CarbonPeriodImmutable/ToArrayTest.php
  tests/CarbonPeriodImmutable/ToDatePeriodTest.php
  tests/CarbonPeriodImmutable/ToStringTest.php
Labels: enhancement

#2762 Handle rounding with cascade factors
  src/Carbon/CarbonInterval.php
  tests/CarbonInterval/RoundingTest.php
Labels: bug
