Repository briannesbitt/Carbon, pull requests merged in 2024-07, with the labels that each got.

#3045 Added period German translations
  src/Carbon/Lang/de.php
Labels: translation

#3051 Use pro rata to calculate decimal part of month/year diffs
  phpstan.neon
  src/Carbon/CarbonInterval.php
  src/Carbon/Traits/Difference.php
  tests/Carbon/DiffTest.php
  tests/Carbon/GettersTest.php
  tests/Carbon/ModifyTest.php
  tests/CarbonImmutable/DiffTest.php
  tests/CarbonInterval/ConstructTest.php
  tests/CarbonInterval/SettersTest.php
  tests/CarbonPeriod/CreateTest.php
Labels: bug

#3052 Accept Unit enum in startOf and endOf
  src/Carbon/Traits/Boundaries.php
  tests/Carbon/StartEndOfTest.php
Labels: enhancement

#3054 Add test for German period translation
  tests/Localization/DeTest.php
Labels: translation

#3053 Add generic methods `isStartOfUnit` and `isEndOfUnit`
  src/Carbon/CarbonInterface.php
  src/Carbon/Traits/Comparison.php
  tests/Carbon/IsTest.php
Labels: enhancement

#3056 Implement isStartOf* and isEndOf* for all units
  phpstan.neon
  src/Carbon/CarbonInterface.php
  src/Carbon/Traits/Boundaries.php
  src/Carbon/Traits/Comparison.php
  tests/Carbon/IsTest.php
  tests/CarbonImmutable/IsTest.php
Labels: enhancement
