Repository briannesbitt/Carbon, pull requests merged in 2024-01, with the labels that each got.

#2909 Remove default interval from toIso8601String output
  src/Carbon/CarbonInterface.php
  src/Carbon/CarbonPeriod.php
  src/Carbon/Factory.php
  src/Carbon/FactoryImmutable.php
  tests/CarbonPeriod/AliasTest.php
  tests/CarbonPeriod/ToStringTest.php
Labels: enhancement

#2912 Consider same "month" only in the same year
  .github/workflows/tests.yml
  phpdoc.php
  src/Carbon/Carbon.php
  src/Carbon/CarbonImmutable.php
  src/Carbon/CarbonInterface.php
  src/Carbon/CarbonInterval.php
  src/Carbon/Traits/Comparison.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Test.php
  tests/AbstractTestCase.php
  tests/Carbon/DiffTest.php
  tests/Carbon/GenericMacroTest.php
  tests/Carbon/IsTest.php
  tests/Carbon/StringsTest.php
  tests/Carbon/TestingAidsTest.php
  tests/CarbonImmutable/DiffTest.php
  tests/CarbonImmutable/GenericMacroTest.php
  tests/CarbonImmutable/IsTest.php
  tests/CarbonImmutable/TestingAidsTest.php
  tests/CarbonInterval/ConstructTest.php
  tests/PHPStan/MacroTest.php
Labels: bug

#2918 Use febr. as Hungarian abbreviation for február (February)
  src/Carbon/Lang/hu.php
Labels: translation

#2923 Fix short year Ukrainian plural
  src/Carbon/Lang/uk.php
  tests/Localization/UkTest.php
  tests/Localization/UkUaTest.php
Labels: translation
