Repository briannesbitt/Carbon, pull requests merged in 2024-04, with the labels that each got.

#2991 Re-allow macro with names starting with diff
  .github/workflows/laravel.yml
  phpstan.neon
  src/Carbon/Traits/Date.php
  tests/Carbon/MacroTest.php
Labels: bug

#2992 Create a dedicated method for each step of the magic __call process
  readme.md
  src/Carbon/CarbonInterface.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Localization.php
Labels: enhancement

#2994 Update Bosnian translations
  src/Carbon/Lang/bs.php
  src/Carbon/Lang/sr.php
  tests/Localization/BsBaTest.php
  tests/Localization/BsCyrlTest.php
  tests/Localization/BsLatnTest.php
  tests/Localization/BsTest.php
  tests/Localization/SrCyrlBaTest.php
  tests/Localization/SrCyrlMeTest.php
  tests/Localization/SrCyrlTest.php
  tests/Localization/SrCyrlXkTest.php
  tests/Localization/SrLatnBaTest.php
  tests/Localization/SrLatnMeTest.php
  tests/Localization/SrLatnTest.php
  tests/Localization/SrLatnXkTest.php
  tests/Localization/SrMeTest.php
  tests/Localization/SrRsLatinTest.php
  tests/Localization/SrRsTest.php
  tests/Localization/SrTest.php
Labels: translation

#2997 Handle null in canBeCreatedFromFormat
  src/Carbon/CarbonInterface.php
  src/Carbon/Traits/Comparison.php
  tests/Carbon/IsTest.php
Labels: bug

#2995 Update Slovak translations
  src/Carbon/Lang/sk.php
Labels: translation

#3001 Add locale and translator options to forHumans and diffForHumans
  src/Carbon/CarbonInterval.php
  src/Carbon/Traits/Difference.php
  src/Carbon/Traits/IntervalRounding.php
  tests/Carbon/LocalizationTest.php
Labels: enhancement

#3007 Fix days for diffForHumans for slovak
  src/Carbon/Lang/sk.php
Labels: translation

#3013 Support %a format
  src/Carbon/CarbonInterval.php
  tests/Carbon/DiffTest.php
  tests/CarbonImmutable/DiffTest.php
Labels: bug

#3005 Fix translator and interval serialization
  phpstan.neon
  src/Carbon/AbstractTranslator.php
  src/Carbon/CarbonInterface.php
  src/Carbon/CarbonInterval.php
  src/Carbon/Traits/Difference.php
  tests/CarbonInterval/ConstructTest.php
  tests/Language/TranslatorTest.php
Labels: bug
