Repository briannesbitt/Carbon, pull requests merged in 2024-02, with the labels that each got.

#2938 Use static values for enums until dropping PHP 8.1
  src/Carbon/Month.php
  src/Carbon/WeekDay.php
Labels: php bug

#2941 Fix Persian translation for before and after
  src/Carbon/Lang/fa.php
  tests/Localization/FaAfTest.php
  tests/Localization/FaIrTest.php
  tests/Localization/FaTest.php
  tests/Localization/MznTest.php
  tests/Localization/UzArabTest.php
Labels: translation

#2943 Document 3.x
  composer.json
  contribute/translate/assets/translations/uk.json
  contribute/translate/assets/translations/uk_UA.json
  docs/index.html
  docs/index.src.html
  index.html
  reference/index.html
  releases.json
  tools/api-history.php
  tools/cache-releases.php
  tools/check.php
  tools/config.php
  tools/functions.php
  tools/generate.php
  tools/methods.php
  tools/release.php
Labels: documentation

#2944 Allow to pass Unit enum for unit name
  .php-cs-fixer.dist.php
  src/Carbon/CarbonInterval.php
  src/Carbon/Traits/Date.php
  src/Carbon/Traits/Difference.php
  src/Carbon/Traits/Units.php
  src/Carbon/Unit.php
  tests/Carbon/AddTest.php
  tests/Carbon/DiffTest.php
  tests/Carbon/GettersTest.php
  tests/Carbon/SettersTest.php
  tests/Jenssegers/TranslationTest.php
Labels: enhancement

#2946 Update PHPDoc
  phpdoc.php
  readme.md
  src/Carbon/Carbon.php
  src/Carbon/CarbonImmutable.php
Labels: documentation
